/**
 * Generated by `scripts/build-coldtest-gallery.mjs`. Do not edit.
 *
 * The number of cold-test rounds, kept separate from the gallery snapshot
 * so client-side copy can cite it without bundling every entry.
 */
export const COLD_TEST_ROUND_COUNT = 171;
