/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { SwatchGroup } from "@gunjo/ui";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

// Demo swatches use design tokens; real product pickers pass any CSS colour.
const swatchOptions = [
  { value: "ink", label: "Ink", color: "hsl(var(--foreground))" },
  { value: "primary", label: "Primary", color: "hsl(var(--primary))" },
  { value: "forest", label: "Forest", color: "hsl(var(--success))" },
  { value: "amber", label: "Amber", color: "hsl(var(--warning))" },
  { value: "muted", label: "Muted (sold out)", color: "hsl(var(--muted))", disabled: true },
];

const usageCode = `import { SwatchGroup } from "@gunjo/ui"

const options = [
  { value: "ink", label: "Ink", color: "hsl(var(--foreground))" },
  { value: "primary", label: "Primary", color: "hsl(var(--primary))" },
  { value: "muted", label: "Muted (sold out)", color: "hsl(var(--muted))", disabled: true },
]

export function Example() {
  const [color, setColor] = React.useState("ink")
  return <SwatchGroup options={options} value={color} onValueChange={setColor} disallowEmpty />
}`;

const propsData = [
  { name: "options", type: "SwatchOption[]", description: "Swatches: { value, label, color, disabled? }." },
  { name: "value", type: "string", description: "Selected swatch value (controlled)." },
  { name: "onValueChange", type: "(value: string) => void", description: "Selection change handler." },
  { name: "size", type: "\"sm\" | \"default\" | \"lg\"", default: "\"default\"", description: "Swatch size." },
  { name: "disallowEmpty", type: "boolean", description: "Keep a selection — clicking the active swatch won't clear it." },
  { name: "className", type: "string", description: "Additional CSS class names." },
];

export default function SwatchGroupDocPage() {
  const title = meta.swatchGroup.title ?? "SwatchGroup";
  const description = meta.swatchGroup.description ?? "";

  return (
    <ComponentLayout title={title} description={description}>
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <SwatchGroup options={swatchOptions} value="primary" />
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
