"use client";

/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import * as React from "react";
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { ComponentDemoStates } from "@/components/doc/ComponentDemoStates";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import { useLocale } from "@/components/providers/LocaleProvider";
import displayMetadata from "@design/display-metadata.json";

import { SwatchGroup } from "@gunjo/ui";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

// Demo swatches use design tokens; real product pickers pass any CSS colour.
const swatchOptions = [
  { value: "ink", label: "Ink", color: "hsl(var(--foreground))" },
  { value: "primary", label: "Primary", color: "hsl(var(--primary))" },
  { value: "forest", label: "Forest", color: "hsl(var(--success))" },
  { value: "amber", label: "Amber", color: "hsl(var(--warning))" },
  { value: "muted", label: "Muted (sold out)", color: "hsl(var(--muted))", disabled: true },
];

const usageCode = `import { SwatchGroup } from "@gunjo/ui"

const options = [
  { value: "ink", label: "Ink", color: "hsl(var(--foreground))" },
  { value: "primary", label: "Primary", color: "hsl(var(--primary))" },
  { value: "muted", label: "Muted (sold out)", color: "hsl(var(--muted))", disabled: true },
]

export function Example() {
  const [color, setColor] = React.useState("ink")
  return <SwatchGroup options={options} value={color} onValueChange={setColor} disallowEmpty />
}`;

const propsData = [
  { name: "options", type: "SwatchOption[]", description: "Swatches: { value, label, color, disabled? }." },
  { name: "value", type: "string", description: "Selected swatch value (controlled)." },
  { name: "onValueChange", type: "(value: string) => void", description: "Selection change handler." },
  { name: "size", type: "\"sm\" | \"default\" | \"lg\"", default: "\"default\"", description: "Swatch size." },
  { name: "disallowEmpty", type: "boolean", description: "Keep a selection — clicking the active swatch won't clear it." },
  { name: "className", type: "string", description: "Additional CSS class names." },
];

// The docs site is not allowed to hardcode colour values, so these demo
// swatches stand in for product data with design tokens.
const palette = [
  { value: "ink", ja: "インク", en: "Ink", color: "hsl(var(--foreground))" },
  { value: "azure", ja: "アズール", en: "Azure", color: "hsl(var(--primary))" },
  { value: "moss", ja: "モス", en: "Moss", color: "hsl(var(--success))" },
  { value: "amber", ja: "アンバー", en: "Amber", color: "hsl(var(--warning))" },
  { value: "coral", ja: "コーラル", en: "Coral", color: "hsl(var(--destructive))" },
];

const SOLD_OUT = ["moss", "coral"];

function ControlledSwatchPreview({ locale }: { locale: "en" | "ja" }) {
  const [colour, setColour] = React.useState("azure");
  const options = palette.map((entry) => ({
    value: entry.value,
    label: locale === "ja" ? entry.ja : entry.en,
    color: entry.color,
  }));
  const selected = options.find((option) => option.value === colour);

  return (
    <div className="flex flex-col items-center gap-3">
      <SwatchGroup
        options={options}
        value={colour}
        onValueChange={setColour}
        disallowEmpty
      />
      <p className="text-sm text-muted-foreground">
        {locale === "ja" ? `色: ${selected?.label}` : `Colour: ${selected?.label}`}
      </p>
    </div>
  );
}

function StockSwatchPreview({ locale }: { locale: "en" | "ja" }) {
  const [colour, setColour] = React.useState("ink");
  const options = palette.map((entry) => {
    const soldOut = SOLD_OUT.includes(entry.value);
    const name = locale === "ja" ? entry.ja : entry.en;
    return {
      value: entry.value,
      label: soldOut
        ? (locale === "ja" ? `${name}（品切れ）` : `${name} (sold out)`)
        : name,
      color: entry.color,
      disabled: soldOut,
    };
  });
  const selected = options.find((option) => option.value === colour);

  return (
    <div className="flex flex-col items-center gap-3">
      <SwatchGroup options={options} value={colour} onValueChange={setColour} />
      <p className="text-sm text-muted-foreground">
        {locale === "ja" ? `色: ${selected?.label}` : `Colour: ${selected?.label}`}
      </p>
    </div>
  );
}

export default function SwatchGroupDocPage() {
  const { locale } = useLocale();
  const title = meta.swatchGroup.title ?? "SwatchGroup";
  const description = meta.swatchGroup.description ?? "";

  const paletteOptions = palette.map((entry) => ({
    value: entry.value,
    label: locale === "ja" ? entry.ja : entry.en,
    color: entry.color,
  }));

  return (
    <ComponentLayout
      title={title}
      description={description}
      usedComponents={[]}
      relatedComponents={[
        { name: "ColorSwatch", href: "/docs/components/color-swatch" },
        { name: "RadioGroup", href: "/docs/components/radio-group" },
        { name: "RadioCard", href: "/docs/components/radio-card" },
        { name: "SegmentedControl", href: "/docs/components/segmented-control" },
      ]}
    >
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <SwatchGroup options={swatchOptions} value="primary" />
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0" id="states">
          {locale === "ja" ? "状態とバリエーション" : "States and variants"}
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {locale === "ja"
            ? "SwatchGroup が変えられるのは、丸の大きさ（size）、選択を誰が持つか（value と onValueChange）、そして選べない色をどう扱うか（options[].disabled）です。丸の中には文字を置かないので、名前は options[].label だけが持ちます。"
            : "Three things vary on a SwatchGroup: the size of each dot, who owns the selection (value with onValueChange), and how unavailable colours behave (options[].disabled). Nothing is printed inside a dot, so options[].label is the only name a swatch has."}
        </p>
        <ComponentDemoStates
          states={[
            {
              key: "size",
              title: locale === "ja" ? "丸の大きさ" : "Dot size",
              description: locale === "ja"
                ? "size は sm・default・lg の3段です。一覧のカードに何色あるかだけを見せるなら sm、商品ページで実際に選ばせるなら default か lg を使います。当たり判定も一緒に変わるので、指で押す画面では小さくしすぎないようにします。"
                : "size runs sm, default, lg. Use sm to show at a glance how many colours a listing card offers, and default or lg where someone actually picks one. The hit area scales with it, so avoid the smallest size on touch screens.",
              preview: (
                <div className="flex flex-col items-center gap-4">
                  <SwatchGroup options={paletteOptions} value="azure" size="sm" />
                  <SwatchGroup options={paletteOptions} value="azure" />
                  <SwatchGroup options={paletteOptions} value="azure" size="lg" />
                </div>
              ),
              code: locale === "ja"
                ? `import { SwatchGroup } from "@gunjo/ui";

const options = [
  { value: "ink", label: "インク", color: "hsl(var(--foreground))" },
  { value: "azure", label: "アズール", color: "hsl(var(--primary))" },
  { value: "moss", label: "モス", color: "hsl(var(--success))" },
];

export function SwatchSizes() {
  return (
    <div className="flex flex-col gap-4">
      <SwatchGroup options={options} value="azure" size="sm" />
      <SwatchGroup options={options} value="azure" />
      <SwatchGroup options={options} value="azure" size="lg" />
    </div>
  );
}`
                : `import { SwatchGroup } from "@gunjo/ui";

const options = [
  { value: "ink", label: "Ink", color: "hsl(var(--foreground))" },
  { value: "azure", label: "Azure", color: "hsl(var(--primary))" },
  { value: "moss", label: "Moss", color: "hsl(var(--success))" },
];

export function SwatchSizes() {
  return (
    <div className="flex flex-col gap-4">
      <SwatchGroup options={options} value="azure" size="sm" />
      <SwatchGroup options={options} value="azure" />
      <SwatchGroup options={options} value="azure" size="lg" />
    </div>
  );
}`,
            },
            {
              key: "disallow-empty",
              title: locale === "ja" ? "選択を必ず1つ残す" : "Always keeping one selected",
              description: locale === "ja"
                ? "value と onValueChange を渡すと選択が画面側のものになり、選んだ色を名前で出したり、その色の写真へ切り替えたりできます。disallowEmpty を足すと、いま選ばれている丸をもう一度押しても外れません。色を選ばないと注文できない商品はこの形にします。"
                : "Passing value with onValueChange moves the selection out to the page, which is what lets you print the chosen colour by name or swap the photo to match. Adding disallowEmpty means clicking the active dot again will not clear it, which is what an order form needs when a colour is mandatory.",
              preview: <ControlledSwatchPreview locale={locale} />,
              code: locale === "ja"
                ? `import * as React from "react";
import { SwatchGroup } from "@gunjo/ui";

const options = [
  { value: "ink", label: "インク", color: "hsl(var(--foreground))" },
  { value: "azure", label: "アズール", color: "hsl(var(--primary))" },
  { value: "moss", label: "モス", color: "hsl(var(--success))" },
];

export function ColourPicker() {
  const [colour, setColour] = React.useState("azure");
  const selected = options.find((option) => option.value === colour);

  return (
    <div className="flex flex-col gap-3">
      <SwatchGroup
        options={options}
        value={colour}
        onValueChange={setColour}
        disallowEmpty
      />
      <p className="text-sm text-muted-foreground">色: {selected?.label}</p>
    </div>
  );
}`
                : `import * as React from "react";
import { SwatchGroup } from "@gunjo/ui";

const options = [
  { value: "ink", label: "Ink", color: "hsl(var(--foreground))" },
  { value: "azure", label: "Azure", color: "hsl(var(--primary))" },
  { value: "moss", label: "Moss", color: "hsl(var(--success))" },
];

export function ColourPicker() {
  const [colour, setColour] = React.useState("azure");
  const selected = options.find((option) => option.value === colour);

  return (
    <div className="flex flex-col gap-3">
      <SwatchGroup
        options={options}
        value={colour}
        onValueChange={setColour}
        disallowEmpty
      />
      <p className="text-sm text-muted-foreground">Colour: {selected?.label}</p>
    </div>
  );
}`,
            },
            {
              key: "sold-out",
              title: locale === "ja" ? "品切れの色を残したまま出す" : "Keeping sold-out colours on show",
              description: locale === "ja"
                ? "disabled にした丸は押せず、矢印キーでも飛ばされます。消さずに残すのは、その色が存在すること自体が買う人には情報だからです。薄く見えることだけが手がかりにならないよう、品切れは label にも書きます。矢印キーで端まで動かすと、選択が品切れの色を飛び越えるのが見えます。"
                : "A disabled dot cannot be clicked and arrow keys step over it. It stays on show because the fact that the colour exists is itself information to a buyer. The dimmed look must not be the only clue, so the state goes into label as well. Arrow through the row and the selection hops over the sold-out dots.",
              preview: <StockSwatchPreview locale={locale} />,
              code: locale === "ja"
                ? `import * as React from "react";
import { SwatchGroup } from "@gunjo/ui";

const options = [
  { value: "ink", label: "インク", color: "hsl(var(--foreground))" },
  { value: "azure", label: "アズール", color: "hsl(var(--primary))" },
  {
    value: "moss",
    label: "モス（品切れ）",
    color: "hsl(var(--success))",
    disabled: true,
  },
  { value: "amber", label: "アンバー", color: "hsl(var(--warning))" },
];

export function StockAwarePicker() {
  const [colour, setColour] = React.useState("ink");
  const selected = options.find((option) => option.value === colour);

  return (
    <div className="flex flex-col gap-3">
      <SwatchGroup options={options} value={colour} onValueChange={setColour} />
      <p className="text-sm text-muted-foreground">色: {selected?.label}</p>
    </div>
  );
}`
                : `import * as React from "react";
import { SwatchGroup } from "@gunjo/ui";

const options = [
  { value: "ink", label: "Ink", color: "hsl(var(--foreground))" },
  { value: "azure", label: "Azure", color: "hsl(var(--primary))" },
  {
    value: "moss",
    label: "Moss (sold out)",
    color: "hsl(var(--success))",
    disabled: true,
  },
  { value: "amber", label: "Amber", color: "hsl(var(--warning))" },
];

export function StockAwarePicker() {
  const [colour, setColour] = React.useState("ink");
  const selected = options.find((option) => option.value === colour);

  return (
    <div className="flex flex-col gap-3">
      <SwatchGroup options={options} value={colour} onValueChange={setColour} />
      <p className="text-sm text-muted-foreground">Colour: {selected?.label}</p>
    </div>
  );
}`,
            },
          ]}
        />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
