import { defineConfig, globalIgnores } from "eslint/config";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

export default defineConfig([
    globalIgnores([
        ".next/**",
        "dist/**",
        "node_modules/**",
        "next-env.d.ts",
        // Regenerated by design-sync scripts; they carry their own eslint-disable banners
        "src/components/**/generated/**",
    ]),
    ...nextCoreWebVitals,
    ...nextTypescript,
    {
        // Same file scope as the "next" config: it does not cover *.cjs, and rule
        // overrides must not reference react-hooks where that plugin is absent
        files: ["**/*.{js,jsx,mjs,ts,tsx,mts,cts}"],
        rules: {
            // Allow the `interface Props extends React.HTMLAttributes<...> {}` pattern
            "@typescript-eslint/no-empty-object-type": [
                "error",
                { allowInterfaces: "with-single-extends" },
            ],
            // React Compiler-era rules: pre-existing violations are tracked in #681.
            // Keep them visible as warnings; restore to "error" once the backlog is cleared.
            "react-hooks/refs": "warn",
            "react-hooks/set-state-in-effect": "warn",
            "react-hooks/static-components": "warn",
            "react-hooks/preserve-manual-memoization": "warn",
            "react-hooks/use-memo": "warn",
            "react-hooks/immutability": "warn",
        },
    },
    {
        // Tailwind config surface is intentionally CJS (tailwind-preset.js is a
        // published export consumed via require)
        files: [
            "tailwind-preset.js",
            "tailwind-theme-extend.cjs",
            "tailwind.config.ts",
        ],
        rules: {
            "@typescript-eslint/no-require-imports": "off",
        },
    },
]);
