function createSyntheticFeedbackVariant(key, overrides = {}) {
  return {
    id: `synthetic:${key}`,
    name: key,
    key,
    type: "frame",
    width: 320,
    height: null,
    padding: [12, 16, 12, 16],
    gap: 4,
    cornerRadius: 8,
    fill: null,
    stroke: null,
    iconFontFamily: null,
    iconFontName: null,
    text: null,
    texts: [],
    reusable: true,
    ...overrides,
  };
}

function createSyntheticFeedbackSpec({ frameId, title, description, variants }) {
  return {
    frameId,
    title,
    description,
    variants,
  };
}

export const FEEDBACK_SPEC_DEFINITIONS = [
  // From atoms (atom-style, no nodeIds)
  {
    key: "alert",
    frameId: "alertFrame",
    titleId: "alertTitle",
    descId: "alertDesc",
    variantsId: "alertVariants",
    additionalVariants: [
      createSyntheticFeedbackVariant("info", {
        name: "Alert/Info",
        width: "fill_container",
        fill: "#eff6ff",
        stroke: { align: "inside", fill: "#bfdbfe", thickness: 1 },
        text: {
          id: "synthetic:alertInfoTitle",
          content: "Information",
          fontSize: 14,
          fontWeight: "500",
          fill: "#1e40af",
          underline: false,
        },
        texts: [
          {
            id: "synthetic:alertInfoTitle",
            content: "Information",
            fontSize: 14,
            fontWeight: "500",
            fill: "#1e40af",
            underline: false,
          },
          {
            id: "synthetic:alertInfoBody",
            content: "Review the latest workspace update.",
            fontSize: 14,
            fontWeight: "normal",
            fill: "#1e3a8a",
            underline: false,
          },
        ],
      }),
      createSyntheticFeedbackVariant("success", {
        name: "Alert/Success",
        width: "fill_container",
        fill: "#f0fdf4",
        stroke: { align: "inside", fill: "#bbf7d0", thickness: 1 },
        text: {
          id: "synthetic:alertSuccessTitle",
          content: "Complete",
          fontSize: 14,
          fontWeight: "500",
          fill: "#166534",
          underline: false,
        },
        texts: [
          {
            id: "synthetic:alertSuccessTitle",
            content: "Complete",
            fontSize: 14,
            fontWeight: "500",
            fill: "#166534",
            underline: false,
          },
          {
            id: "synthetic:alertSuccessBody",
            content: "The workspace is ready.",
            fontSize: 14,
            fontWeight: "normal",
            fill: "#14532d",
            underline: false,
          },
        ],
      }),
      createSyntheticFeedbackVariant("warning", {
        name: "Alert/Warning",
        width: "fill_container",
        fill: "#fef3c7",
        stroke: { align: "inside", fill: "#fcd34d", thickness: 1 },
        text: {
          id: "synthetic:alertWarningTitle",
          content: "Attention",
          fontSize: 14,
          fontWeight: "500",
          fill: "#78350f",
          underline: false,
        },
        texts: [
          {
            id: "synthetic:alertWarningTitle",
            content: "Attention",
            fontSize: 14,
            fontWeight: "500",
            fill: "#78350f",
            underline: false,
          },
          {
            id: "synthetic:alertWarningBody",
            content: "Confirm the setting before continuing.",
            fontSize: 14,
            fontWeight: "normal",
            fill: "#78350f",
            underline: false,
          },
        ],
      }),
    ],
  },
  {
    key: "progress",
    frameId: "progressFrame",
    titleId: "progressTitle",
    descId: "progressDesc",
    variantsId: "progressVariants",
  },
  {
    key: "statusScreen",
    syntheticSpec: createSyntheticFeedbackSpec({
      frameId: "synthetic:statusScreen",
      title: "StatusScreen",
      description:
        "Full-page status feedback for not-found, error, offline, forbidden, maintenance, and coming-soon states.",
      variants: [
        createSyntheticFeedbackVariant("not-found", {
          name: "StatusScreen/Not found",
          width: "fill_container",
          padding: [32, 32, 32, 32],
          gap: null,
          cornerRadius: null,
          texts: [
            {
              id: "synthetic:statusScreenNotFoundCode",
              content: "404",
              fontSize: 72,
              fontWeight: "800",
              fill: "hsl(var(--foreground))",
              underline: false,
            },
            {
              id: "synthetic:statusScreenNotFoundTitle",
              content: "Page not found",
              fontSize: 24,
              fontWeight: "600",
              fill: "hsl(var(--foreground))",
              underline: false,
            },
          ],
        }),
        createSyntheticFeedbackVariant("error", {
          name: "StatusScreen/Error",
          width: "fill_container",
          padding: [32, 32, 32, 32],
          gap: null,
          cornerRadius: null,
          texts: [
            {
              id: "synthetic:statusScreenErrorCode",
              content: "500",
              fontSize: 72,
              fontWeight: "800",
              fill: "hsl(var(--destructive))",
              underline: false,
            },
            {
              id: "synthetic:statusScreenErrorTitle",
              content: "Something went wrong",
              fontSize: 24,
              fontWeight: "600",
              fill: "hsl(var(--foreground))",
              underline: false,
            },
          ],
        }),
        createSyntheticFeedbackVariant("offline", {
          name: "StatusScreen/Offline",
          width: "fill_container",
          padding: [32, 32, 32, 32],
          gap: null,
          cornerRadius: null,
        }),
        createSyntheticFeedbackVariant("forbidden", {
          name: "StatusScreen/Forbidden",
          width: "fill_container",
          padding: [32, 32, 32, 32],
          gap: null,
          cornerRadius: null,
        }),
        createSyntheticFeedbackVariant("maintenance", {
          name: "StatusScreen/Maintenance",
          width: "fill_container",
          padding: [32, 32, 32, 32],
          gap: null,
          cornerRadius: null,
        }),
        createSyntheticFeedbackVariant("coming-soon", {
          name: "StatusScreen/Coming soon",
          width: "fill_container",
          padding: [32, 32, 32, 32],
          gap: null,
          cornerRadius: null,
        }),
      ],
    }),
  },
  {
    key: "spinner",
    frameId: "spinnerFrame",
    titleId: "spinnerTitle",
    descId: "spinnerDesc",
    variantsId: "spinnerVariants",
  },
  // From molecules (structured style)
  {
    key: "toast",
    frameId: "toastFrame",
    titleId: "toastTitle",
    descId: "toastDesc",
    variantsId: "toastVariants",
    nodeIds: {
      success: "toastSuccess",
      successIcon: "toastSuccessIcon",
      successText: "toastSuccessText",
      successClose: "toastSuccessClose",
      error: "toastError",
      errorIcon: "toastErrorIcon",
      errorText: "toastErrorText",
      info: "toastInfo",
      infoIcon: "toastInfoIcon",
      infoText: "toastInfoText",
    },
  },
  {
    key: "notificationCenter",
    frameId: "notificationCenterFrame",
    titleId: "notificationCenterTitle",
    descId: "notificationCenterDesc",
    variantsId: "notificationCenterVariants",
    nodeIds: {
      default: "notificationCenterDefault",
      trigger: "notificationCenterTrigger",
      bellIcon: "notificationCenterBellIcon",
      unreadDot: "notificationCenterUnreadDot",
      panel: "notificationCenterPanel",
      header: "notificationCenterHeader",
      listItem: "notificationCenterListItem",
      footerButton: "notificationCenterFooterButton",
    },
  },
  {
    key: "statusBar",
    frameId: "statusBarFrame",
    titleId: "statusBarTitle",
    descId: "statusBarDesc",
    variantsId: "statusBarVariants",
    nodeIds: {
      default: "statusBarDefault",
      left: "statusBarLeft",
      center: "statusBarCenter",
      right: "statusBarRight",
    },
  },
  {
    key: "progressWidget",
    frameId: "progressWidgetFrame",
    titleId: "progressWidgetTitle",
    descId: "progressWidgetDesc",
    variantsId: "progressWidgetVariants",
    nodeIds: {
      default: "progressWidgetDefault",
      header: "progressWidgetHeader",
      headerTitle: "progressWidgetHeaderTitle",
      content: "progressWidgetContent",
      value: "progressWidgetValue",
      progress: "progressWidgetProgress",
      subtext: "progressWidgetSubtext",
    },
  },
  {
    key: "stepper",
    frameId: "SZumS",
    titleId: "U5TkhC",
    descId: "QZuuw",
    variantsId: "SZumS",
    nodeIds: {},
  },
  {
    key: "banner",
    frameId: "DDYIe",
    titleId: "X4KpL",
    descId: "d1jA6",
    variantsId: "DDYIe",
    nodeIds: {},
  },
  // From organisms (structured style)
  {
    key: "toastProvider",
    frameId: "toastProviderFrame",
    titleId: "toastProviderTitle",
    descId: "toastProviderDesc",
    variantsId: "toastProviderVariants",
    nodeIds: {
      default: "toastProviderDefault",
      stack: "toastProviderStack",
      item: "toastProviderItem",
      itemText: "toastProviderItemText",
      defaultDuration: "toastProviderDefaultDuration",
      exitDelay: "toastProviderExitDelay",
    },
  },
];
