function createSyntheticInputsSpec({ frameId, title, description, variants, composition, notes }) {
  return {
    frameId,
    title,
    description,
    variants,
    ...(composition ? { composition } : {}),
    ...(notes ? { notes } : {}),
  };
}

function createSyntheticVariant(key, overrides = {}) {
  return {
    id: `synthetic:${key}`,
    name: key,
    key,
    type: "frame",
    width: "fill_container",
    height: null,
    padding: [0, 0, 0, 0],
    gap: null,
    cornerRadius: null,
    fill: null,
    stroke: null,
    text: null,
    texts: [],
    children: [],
    reusable: true,
    ...overrides,
  };
}

export const INPUTS_SPEC_DEFINITIONS = [
  // From atoms — atom-style (no nodeIds)
  {
    key: "button",
    frameId: "buttonFrame",
    titleId: "buttonTitle",
    descId: "buttonDesc",
    variantsId: "buttonVariants",
    additionalVariants: [
      createSyntheticVariant("primary", {
        name: "Button/Primary",
        width: null,
        height: 36,
        padding: [8, 16, 8, 16],
        gap: 8,
        cornerRadius: 8,
        fill: "#394794",
        text: {
          id: "synthetic:buttonPrimaryText",
          content: "Primary",
          fontSize: 14,
          fontWeight: "500",
          fill: "#f8fafc",
          underline: false,
        },
      }),
      createSyntheticVariant("info", {
        name: "Button/Info",
        width: null,
        height: 36,
        padding: [8, 16, 8, 16],
        gap: 8,
        cornerRadius: 8,
        fill: "#1d4ed8",
        text: {
          id: "synthetic:buttonInfoText",
          content: "Info",
          fontSize: 14,
          fontWeight: "500",
          fill: "#f8fafc",
          underline: false,
        },
      }),
      createSyntheticVariant("success", {
        name: "Button/Success",
        width: null,
        height: 36,
        padding: [8, 16, 8, 16],
        gap: 8,
        cornerRadius: 8,
        fill: "#15803d",
        text: {
          id: "synthetic:buttonSuccessText",
          content: "Success",
          fontSize: 14,
          fontWeight: "500",
          fill: "#f8fafc",
          underline: false,
        },
      }),
      createSyntheticVariant("warning", {
        name: "Button/Warning",
        width: null,
        height: 36,
        padding: [8, 16, 8, 16],
        gap: 8,
        cornerRadius: 8,
        fill: "#b45309",
        text: {
          id: "synthetic:buttonWarningText",
          content: "Warning",
          fontSize: 14,
          fontWeight: "500",
          fill: "#f8fafc",
          underline: false,
        },
      }),
    ],
  },
  {
    key: "tooltipButton",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:tooltipButton",
      title: "TooltipButton",
      description: "Button composition that pairs an action with a GunjoUI Tooltip for icon, compact, or explanatory controls.",
      variants: [
        createSyntheticVariant("default", {
          width: null,
          padding: null,
        }),
      ],
    }),
  },
  {
    key: "copyButton",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:copyButton",
      title: "CopyButton",
      description: "Clipboard action button with tooltip feedback and copied-state icon or label.",
      variants: [
        createSyntheticVariant("default", {
          width: null,
          padding: null,
        }),
        createSyntheticVariant("label", {
          width: null,
          padding: null,
        }),
      ],
    }),
  },
  {
    key: "chatInput",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:chatInput",
      title: "ChatInput",
      description: "Message composer with multiline input, attachment action, send/stop controls, and disabled-state feedback.",
      variants: [
        createSyntheticVariant("default", {
          width: "fill_container",
          padding: [12, 12, 12, 12],
          gap: 8,
          fill: "#ffffff",
          stroke: "#e2e8f0",
        }),
        createSyntheticVariant("processing", {
          width: "fill_container",
          padding: [12, 12, 12, 12],
          gap: 8,
          fill: "#ffffff",
          stroke: "#e2e8f0",
        }),
      ],
    }),
  },
  {
    key: "chatComposer",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:chatComposer",
      title: "ChatComposer",
      description: "Container that composes ChatInput with prompt choices, workspace context, usage status, footer context, or an accessory.",
      variants: [
        createSyntheticVariant("default", {
          width: "fill_container",
          padding: [0, 0, 0, 0],
          gap: 12,
        }),
        createSyntheticVariant("context", {
          width: "fill_container",
          padding: [0, 0, 0, 0],
          gap: 12,
        }),
        createSyntheticVariant("prompt", {
          width: "fill_container",
          padding: [0, 0, 0, 0],
          gap: 12,
        }),
      ],
    }),
  },
  {
    key: "input",
    frameId: "inputFrame",
    titleId: "inputTitle",
    descId: "inputDesc",
    variantsId: "inputVariants",
    variantOverrides: {
      default: { width: "fill_container" },
      placeholder: { width: "fill_container" },
      disabled: { width: "fill_container" },
    },
  },
  { key: "label", frameId: "labelFrame", titleId: "labelTitle", descId: "labelDesc", sampleTextId: "labelDefaultText" },
  { key: "checkbox", frameId: "checkboxFrame", titleId: "checkboxTitle", descId: "checkboxDesc", variantsId: "checkboxVariants" },
  { key: "switch", frameId: "switchFrame", titleId: "switchTitle", descId: "switchDesc", variantsId: "switchVariants" },
  {
    key: "textarea",
    frameId: "textareaFrame",
    titleId: "textareaTitle",
    descId: "textareaDesc",
    variantsId: "textareaVariants",
    variantOverrides: {
      default: { width: "fill_container", text: null, texts: [] },
      disabled: { width: "fill_container", text: null, texts: [] },
    },
  },
  { key: "radioGroup", frameId: "radioGroupFrame", titleId: "radioGroupTitle", descId: "radioGroupDesc", variantsId: "radioGroupVariants" },
  { key: "slider", frameId: "sliderFrame", titleId: "sliderTitle", descId: "sliderDesc", variantsId: "sliderVariants" },
  { key: "rangeSlider", frameId: "rangeSliderFrame", titleId: "rangeSliderTitle", descId: "rangeSliderDesc", variantsId: "rangeSliderVariants" },
  {
    key: "select",
    frameId: "selectFrame",
    titleId: "selectTitle",
    descId: "selectDesc",
    variantsId: "selectVariants",
    variantOverrides: {
      default: { width: "fill_container", height: 36 },
    },
  },
  { key: "toggleGroup", frameId: "toggleGroupFrame", titleId: "toggleGroupTitle", descId: "toggleGroupDesc", variantsId: "toggleGroupVariants" },
  { key: "toggle", frameId: "thTjM", titleId: "SNSrY", descId: "GnIcm", variantsId: "thTjM" },
  { key: "numberInput", frameId: "j38LFp", titleId: "h9AQf", descId: "NiBX0", variantsId: "j38LFp" },
  { key: "passwordInput", frameId: "rne63", titleId: "STrTJ", descId: "VNfkV", variantsId: "rne63" },
  {
    key: "passwordRequirementList",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:passwordRequirementList",
      title: "PasswordRequirementList",
      description: "Password requirement checklist that can be used standalone or inside PasswordGroup.",
      variants: [],
      composition: {
        canonicalLayout: "vertical-checklist",
        publicParts: ["PasswordRequirementList"],
        stateKeys: ["pending", "met", "unmet"],
      },
      notes: [
        "PasswordInput does not own fixed password rules.",
        "Pass requirement labels and met states from product validation logic.",
      ],
    }),
  },
  {
    key: "passwordStrengthMeter",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:passwordStrengthMeter",
      title: "PasswordStrengthMeter",
      description: "Password strength meter that displays a caller-provided score, label, and helper text.",
      variants: [],
      composition: {
        canonicalLayout: "segmented-meter",
        publicParts: ["PasswordStrengthMeter"],
        scoreRange: "0..maxScore",
      },
      notes: [
        "The component renders strength state but does not calculate password entropy.",
        "Callers provide score, label, and descriptions from their validation policy.",
      ],
    }),
  },
  {
    key: "passwordGroup",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:passwordGroup",
      title: "PasswordGroup",
      description: "Password field composition with visibility control, requirement checklist, strength meter, error message, and disabled feedback.",
      variants: [],
      composition: {
        canonicalLayout: "vertical-field-group",
        publicParts: [
          "PasswordGroup",
          "PasswordInput",
          "PasswordRequirementList",
          "PasswordStrengthMeter",
          "FormGroup",
        ],
        defaultGap: 6,
      },
      notes: [
        "Use PasswordGroup when requirements or strength feedback are part of the same password field.",
        "Use PasswordInput alone when a simple secret value input is enough.",
      ],
    }),
  },
  {
    key: "phoneInput",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:phoneInput",
      title: "PhoneInput",
      description: "Telephone input with country calling-code affordance and caller-provided formatting hook.",
      variants: [],
      composition: {
        canonicalLayout: "prefix-input",
        publicParts: ["PhoneInput", "Input"],
        controlHeight: 36,
      },
      notes: [
        "The default formatter supports common Japanese mobile-style grouping.",
        "Use formatValue for product-specific or international phone-number formatting.",
      ],
    }),
  },
  {
    key: "postalCodeInput",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:postalCodeInput",
      title: "PostalCodeInput",
      description: "Postal-code input with prefix affordance and caller-provided formatting hook.",
      variants: [],
      composition: {
        canonicalLayout: "prefix-input",
        publicParts: ["PostalCodeInput", "Input"],
        controlHeight: 36,
      },
      notes: [
        "The default formatter supports Japanese 3-4 postal-code grouping.",
        "Address lookup or autofill should be composed above this input.",
      ],
    }),
  },
  { key: "searchInput", frameId: "J5BDKM", titleId: "KupFr", descId: "x0y0cN", variantsId: "J5BDKM" },
  { key: "inputOTP", frameId: "N4befa", titleId: "HyucP", descId: "mI1og", variantsId: "N4befa" },
  // From molecules — structured (with nodeIds)
  {
    key: "calendar",
    frameId: "calendarFrame",
    titleId: "calendarTitle",
    descId: "calendarDesc",
    variantsId: "calendarVariants",
    nodeIds: {
      default: "calendarDefault",
      header: "calendarHeader",
      month: "calendarMonth",
      grid: "calendarGrid",
    },
  },
  {
    key: "filterButton",
    frameId: "filterButtonFrame",
    titleId: "filterButtonTitle",
    descId: "filterButtonDesc",
    variantsId: "filterButtonVariants",
    nodeIds: {
      default: "filterButtonDefault",
      selected: "filterButtonSelected",
      popover: "filterButtonPopover",
      icon: "filterButtonIcon",
      label: "filterButtonLabel",
      badge: "filterButtonBadge",
      commandItem: "filterButtonCommandItem",
      checkBox: "filterButtonCheckBox",
      divider: "filterButtonDivider",
    },
  },
  {
    key: "sortButton",
    frameId: "sortButtonFrame",
    titleId: "sortButtonTitle",
    descId: "sortButtonDesc",
    variantsId: "sortButtonVariants",
    nodeIds: {
      none: "sortButtonNone",
      asc: "sortButtonAsc",
      desc: "sortButtonDescending",
      icon: "sortButtonIcon",
      label: "sortButtonLabel",
    },
  },
  {
    key: "editableField",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:editableField",
      title: "Editable Field",
      description: "Labelled field that switches between read-only display and explicit save/cancel editing.",
      variants: [
        createSyntheticVariant("default"),
      ],
    }),
  },
  {
    key: "form",
    syntheticSpec: createSyntheticInputsSpec({
      frameId: "synthetic:form",
      title: "Form",
      description: "Compound form primitives for vertical field composition, labels, descriptions, messages, and full-width controls.",
      composition: {
        canonicalLayout: "vertical-field-group",
        publicParts: [
          "Form",
          "FormField",
          "FormGroup",
          "FormLabel",
          "FormControl",
          "FormDescription",
          "FormMessage",
        ],
        controlHeight: 36,
        defaultGap: 6,
        fieldGap: 16,
        fullWidthControlSlots: [
          "combobox",
          "date-picker",
          "date-range-picker",
          "editable-field",
          "file-uploader",
          "input",
          "input-otp",
          "mention",
          "number-input",
          "password-group",
          "password-input",
          "phone-input",
          "postal-code-input",
          "range-slider",
          "search-input",
          "select-control",
          "slider",
          "tag-input",
          "textarea",
          "time-picker",
        ],
      },
      notes: [
        "Standalone Input, Textarea, Select, Slider, and related controls keep their intrinsic preview width.",
        "Inside FormGroup, controls expand to the field width through data-slot selectors instead of one-off docs wrappers.",
        "The canonical form control height remains 36px / h-9 unless a specific component documents a larger touch target.",
      ],
      variants: [],
    }),
  },
  { key: "combobox", frameId: "vuR8V", titleId: "GhqSM", descId: "qUQs9", variantsId: "vuR8V", nodeIds: {} },
  { key: "datePicker", frameId: "RZOgR", titleId: "lua55", descId: "Aq49k", variantsId: "RZOgR", nodeIds: {} },
  { key: "dateRangePicker", frameId: "kDPmC", titleId: "BydVI", descId: "dj5KI", variantsId: "kDPmC", nodeIds: {} },
  { key: "timePicker", frameId: "iKAYe", titleId: "Nq2tH", descId: "HNQTF", variantsId: "iKAYe", nodeIds: {} },
  { key: "tagInput", frameId: "howAc", titleId: "HPBNU", descId: "u9OEVf", variantsId: "howAc", nodeIds: {} },
  { key: "mention", frameId: "Fhg5j", titleId: "Ex2OK", descId: "zNez1", variantsId: "Fhg5j", nodeIds: {} },
  // From organisms — structured (with nodeIds)
  {
    key: "fileUploader",
    frameId: "fileUploaderFrame",
    titleId: "fileUploaderTitle",
    descId: "fileUploaderDesc",
    variantsId: "fileUploaderVariants",
    nodeIds: {
      default: "fileUploaderDefault",
      dropzone: "fileUploaderDropzone",
      icon: "fileUploaderIcon",
      prompt: "fileUploaderPrompt",
      hint: "fileUploaderHint",
      item: "fileUploaderItem",
      itemName: "fileUploaderItemName",
    },
  },
];
