export const NAVIGATION_SPEC_DEFINITIONS = [
  // From molecules
  {
    key: "textLink",
    syntheticSpec: {
      frameId: "synthetic:textLink",
      title: "TextLink",
      description: "Inline text link that automatically shows an external-tab icon when it opens a new tab.",
      variants: [
        {
          id: "synthetic:textLinkDefault",
          name: "TextLink/Default",
          key: "default",
          type: "frame",
          width: null,
          height: null,
          padding: [0, 0, 0, 0],
          gap: 4,
          cornerRadius: null,
          fill: null,
          stroke: null,
          text: {
            fontSize: 14,
            fontWeight: 500,
            content: "Text link",
            fill: "#2563eb",
          },
          texts: [],
          children: [],
          reusable: true,
        },
        {
          id: "synthetic:textLinkMuted",
          name: "TextLink/Muted",
          key: "muted",
          type: "frame",
          width: null,
          height: null,
          padding: [0, 0, 0, 0],
          gap: 4,
          cornerRadius: null,
          fill: null,
          stroke: null,
          text: {
            fontSize: 14,
            fontWeight: 500,
            content: "Text link",
            fill: "#0f172a",
          },
          texts: [],
          children: [],
          reusable: true,
        },
      ],
    },
  },
  {
    key: "breadcrumb",
    frameId: "breadcrumbFrame",
    titleId: "breadcrumbTitle",
    descId: "breadcrumbDesc",
    variantsId: "breadcrumbVariants",
    nodeIds: {
      default: "breadcrumbDefault",
      link1: "breadcrumbLink1",
      sep1: "breadcrumbSep1",
      link2: "breadcrumbLink2",
      sep2: "breadcrumbSep2",
      page: "breadcrumbPage",
    },
  },
  {
    key: "tabs",
    frameId: "tabsFrame",
    titleId: "tabsTitle",
    descId: "tabsDesc",
    variantsId: "tabsVariants",
    nodeIds: {
      default: "tabsDefault",
      list: "tabsList",
      triggerActive: "tabsTriggerActive",
      triggerActiveText: "tabsTriggerActiveText",
      trigger: "tabsTrigger",
      triggerText: "tabsTriggerText",
      content: "tabsContent",
      contentText: "tabsContentText",
    },
  },
  {
    key: "pagination",
    frameId: "paginationFrame",
    titleId: "paginationTitle",
    descId: "paginationDesc",
    variantsId: "paginationVariants",
    nodeIds: {
      default: "paginationDefault",
      content: "paginationContent",
      previous: "paginationPrevious",
      ellipsis: "paginationEllipsis",
      next: "paginationNext",
    },
  },
  {
    key: "documentPager",
    syntheticSpec: {
      frameId: "documentPagerFrame",
      title: "DocumentPager",
      description:
        "Adjacent-document navigation with preview thumbnail, category label, title, and description.",
      variants: [
        {
          id: "documentPagerDefault",
          name: "DocumentPager/Default",
          key: "default",
          type: "frame",
          width: "fill_container",
          height: null,
          padding: [20, 0, 0, 0],
          gap: 12,
          cornerRadius: null,
          fill: null,
          stroke: "#e2e8f0",
          reusable: true,
          children: ["documentPagerPrevious", "documentPagerNext"],
        },
      ],
      nodes: {
        default: {
          id: "documentPagerDefault",
          type: "frame",
          name: "DocumentPager/Default",
          width: "fill_container",
          height: null,
          padding: [20, 0, 0, 0],
          gap: 12,
          cornerRadius: null,
          fill: null,
          stroke: "#e2e8f0",
          justifyContent: null,
          alignItems: null,
          fontSize: null,
          fontWeight: null,
          content: null,
          iconFontFamily: null,
          iconFontName: null,
          textGrowth: null,
          children: ["documentPagerPrevious", "documentPagerNext"],
        },
        previous: {
          id: "documentPagerPrevious",
          type: "frame",
          name: "DocumentPager/Previous",
          width: "fill_container",
          height: null,
          padding: [12, 12, 12, 12],
          gap: 12,
          cornerRadius: 6,
          fill: "#ffffff",
          stroke: "#e2e8f0",
          justifyContent: null,
          alignItems: null,
          fontSize: null,
          fontWeight: null,
          content: null,
          iconFontFamily: null,
          iconFontName: null,
          textGrowth: null,
          children: [],
        },
        next: {
          id: "documentPagerNext",
          type: "frame",
          name: "DocumentPager/Next",
          width: "fill_container",
          height: null,
          padding: [12, 12, 12, 12],
          gap: 12,
          cornerRadius: 6,
          fill: "#ffffff",
          stroke: "#e2e8f0",
          justifyContent: null,
          alignItems: null,
          fontSize: null,
          fontWeight: null,
          content: null,
          iconFontFamily: null,
          iconFontName: null,
          textGrowth: null,
          children: [],
        },
      },
    },
  },
  {
    key: "navigationMenu",
    frameId: "aMzv9",
    titleId: "gfmkG",
    descId: "ERS0P",
    variantsId: "aMzv9",
    nodeIds: {},
  },
  {
    key: "sidebar",
    frameId: "V0XxoV",
    titleId: "G8MpzT",
    descId: "s2VQ30",
    variantsId: "V0XxoV",
    nodeIds: {},
  },
  {
    key: "sidebarItem",
    frameId: "sidebarItemFrame",
    titleId: "sidebarItemTitle",
    descId: "sidebarItemDesc",
    variantsId: "sidebarItemVariants",
    nodeIds: {
      default: "sidebarItemDefault",
      active: "sidebarItemActive",
      content: "sidebarItemContent",
      chevronSlot: "sidebarItemChevronSlot",
      iconSlot: "sidebarItemIconSlot",
      label: "sidebarItemLabel",
      right: "sidebarItemRight",
      delete: "sidebarItemDelete",
      count: "sidebarItemCount",
    },
    componentOverrides: {
      interaction: {
        cursor: "pointer",
      },
    },
  },
  {
    key: "menubar",
    frameId: "menubarFrame",
    titleId: "menubarTitle",
    descId: "menubarDesc",
    variantsId: "menubarVariants",
    nodeIds: {
      default: "menubarDefault",
      trigger: "menubarTrigger",
      content: "menubarContent",
      item: "menubarItem",
      separator: "menubarSeparator",
      subTrigger: "menubarSubTrigger",
    },
  },
  {
    key: "command",
    frameId: "commandFrame",
    titleId: "commandTitle",
    descId: "commandDesc",
    variantsId: "commandVariants",
    nodeIds: {
      default: "commandDefault",
      input: "commandInput",
      inputPlaceholder: "commandInputPlaceholder",
      list: "commandList",
      groupHeading: "commandGroupHeading",
      item: "commandItem",
    },
  },
  // From organisms
  {
    key: "appRail",
    frameId: "appRailFrame",
    titleId: "appRailTitle",
    descId: "appRailDesc",
    variantsId: "appRailVariants",
    nodeIds: {
      default: "appRailDefault",
      iconHome: "appRailIconHome",
      iconSearch: "appRailIconSearch",
      iconFolder: "appRailIconFolder",
    },
  },
  {
    key: "commandPalette",
    frameId: "commandPaletteFrame",
    titleId: "commandPaletteTitle",
    descId: "commandPaletteDesc",
    variantsId: "commandPaletteVariants",
    nodeIds: {
      default: "commandPaletteDefault",
      input: "commandPaletteInput",
      inputPlaceholder: "commandPaletteInputPlaceholder",
      group: "commandPaletteGroup",
      groupHeading: "commandPaletteGroupHeading",
      item: "commandPaletteItem",
      itemLabel: "commandPaletteItemLabel",
      itemShortcut: "commandPaletteItemShortcut",
    },
  },
  {
    key: "rightRail",
    frameId: "rightRailFrame",
    titleId: "rightRailTitle",
    descId: "rightRailDesc",
    variantsId: "rightRailVariants",
    nodeIds: {
      default: "rightRailDefault",
      header: "rightRailHeader",
      headerText: "rightRailHeaderText",
      item: "rightRailItem",
      itemText: "rightRailItemText",
    },
  },
  {
    key: "pageAside",
    syntheticSpec: {
      frameId: "synthetic:pageAside",
      title: "PageAside",
      description:
        "Responsive page support layout that renders supporting information as a right rail on wide screens and a collapsible block on narrow screens.",
      variants: [
        {
          id: "synthetic:pageAsideDefault",
          name: "PageAside/Default",
          key: "default",
          type: "frame",
          width: "fill_container",
          height: null,
          padding: [0, 0, 0, 0],
          gap: 24,
          cornerRadius: null,
          fill: null,
          stroke: null,
          reusable: true,
          children: [],
        },
      ],
    },
  },
  {
    key: "header",
    frameId: "n0CoF",
    titleId: "NLo20",
    descId: "MpEOb",
    variantsId: "n0CoF",
    nodeIds: {},
  },
  {
    key: "footer",
    frameId: "fXprq",
    titleId: "xeYDz",
    descId: "SGaOy",
    variantsId: "fXprq",
    nodeIds: {},
  },
];
