export const PATTERNS_SPEC_DEFINITIONS = [
  {
    key: "dashboardTemplate",
    frameId: "dashboardTemplateFrame",
    titleId: "dashboardTemplateTitle",
    descId: "dashboardTemplateDesc",
    variantsId: "dashboardTemplateVariants",
    nodeIds: {
      default: "dashboardTemplateDefault",
      header: "dashboardTemplateHeader",
      body: "dashboardTemplateBody",
      sidebar: "dashboardTemplateSidebar",
      main: "dashboardTemplateMain",
      content: "dashboardTemplateContent",
    },
  },
  {
    key: "editorTemplate",
    frameId: "editorTemplateFrame",
    titleId: "editorTemplateTitle",
    descId: "editorTemplateDesc",
    variantsId: "editorTemplateVariants",
    nodeIds: {
      default: "editorTemplateDefault",
      topBar: "editorTemplateTopBar",
      body: "editorTemplateBody",
      leftPanel: "editorTemplateLeftPanel",
      canvas: "editorTemplateCanvas",
      rightPanel: "editorTemplateRightPanel",
    },
  },
  {
    key: "landingTemplate",
    frameId: "landingTemplateFrame",
    titleId: "landingTemplateTitle",
    descId: "landingTemplateDesc",
    variantsId: "landingTemplateVariants",
    nodeIds: {
      default: "landingTemplateDefault",
      header: "landingTemplateHeader",
      hero: "landingTemplateHero",
      featureSection: "landingTemplateFeatureSection",
    },
  },
  {
    key: "authTemplate",
    frameId: "authTemplateFrame",
    titleId: "authTemplateTitle",
    descId: "authTemplateDesc",
    variantsId: "authTemplateVariants",
    nodeIds: {
      default: "authTemplateDefault",
      visualPanel: "authTemplateVisualPanel",
      formPanel: "authTemplateFormPanel",
      formContainer: "authTemplateFormContainer",
    },
  },
  {
    key: "responsiveAuthCardPattern",
    frameId: "E6FlLl",
    titleId: "MH71f",
    descId: "Imn3A",
    variantsId: "W4jaj",
    nodeIds: {
      default: "x3Hma",
      header: "T1VaJ",
      tabs: "HlI3Z",
      card: "dg3KD",
      terms: "DTyPr",
    },
  },
  {
    key: "kanbanTemplate",
    frameId: "kanbanTemplateFrame",
    titleId: "kanbanTemplateTitle",
    descId: "kanbanTemplateDesc",
    variantsId: "kanbanTemplateVariants",
    nodeIds: {
      default: "kanbanTemplateDefault",
      sidebar: "kanbanTemplateSidebar",
      main: "kanbanTemplateMain",
      header: "kanbanTemplateHeader",
      board: "kanbanTemplateBoard",
      columns: "kanbanTemplateColumns",
    },
  },
  {
    key: "chatTemplate",
    frameId: "chatTemplateFrame",
    titleId: "chatTemplateTitle",
    descId: "chatTemplateDesc",
    variantsId: "chatTemplateVariants",
    nodeIds: {
      default: "chatTemplateDefault",
      sidebarList: "chatTemplateSidebarList",
      mainArea: "chatTemplateMainArea",
      header: "chatTemplateHeader",
      messages: "chatTemplateMessages",
      composer: "chatTemplateComposer",
      sidebarDetail: "chatTemplateSidebarDetail",
    },
  },
  {
    key: "settingsTemplate",
    frameId: "settingsTemplateFrame",
    titleId: "settingsTemplateTitle",
    descId: "settingsTemplateDesc",
    variantsId: "settingsTemplateVariants",
    nodeIds: {
      default: "settingsTemplateDefault",
      mobileView: "settingsTemplateMobileView",
      desktopView: "settingsTemplateDesktopView",
      desktopTitle: "settingsTemplateDesktopTitle",
      separator: "settingsTemplateSeparator",
      desktopBody: "settingsTemplateDesktopBody",
      nav: "settingsTemplateNav",
      content: "settingsTemplateContent",
    },
  },
  {
    key: "bannalyzeTemplate",
    frameId: "bannalyzeTemplateFrame",
    titleId: "bannalyzeTemplateTitle",
    descId: "bannalyzeTemplateDesc",
    variantsId: "bannalyzeTemplateVariants",
    nodeIds: {
      default: "bannalyzeTemplateDefault",
      header: "bannalyzeTemplateHeader",
      body: "bannalyzeTemplateBody",
      sidebar: "bannalyzeTemplateSidebar",
      canvas: "bannalyzeTemplateCanvas",
      canvasInner: "bannalyzeTemplateCanvasInner",
      inspector: "bannalyzeTemplateInspector",
    },
  },
  {
    key: "mediaLibraryTemplate",
    frameId: "mediaLibraryTemplateFrame",
    titleId: "mediaLibraryTemplateTitle",
    descId: "mediaLibraryTemplateDesc",
    variantsId: "mediaLibraryTemplateVariants",
    nodeIds: {
      default: "mediaLibraryTemplateDefault",
      header: "mediaLibraryTemplateHeader",
      body: "mediaLibraryTemplateBody",
      sidebar: "mediaLibraryTemplateSidebar",
      gridArea: "mediaLibraryTemplateGridArea",
      gridInner: "mediaLibraryTemplateGridInner",
      details: "mediaLibraryTemplateDetails",
    },
  },
  {
    key: "pricingTemplate",
    frameId: "hGE07",
    titleId: "WXQiF",
    descId: "PuN7Y",
    variantsId: "nqx5v",
    useDocumentRoot: true,
    nodeIds: {
      header: "zBlUu",
      eyebrow: "E0AKv",
      default: "hkX7r",
      billingControls: "j0i4u",
      billingCaption: "x0LtUI",
      billingToggle: "xg1Ll",
      monthlySegment: "j47wA",
      monthlyLabel: "LrxUj",
      yearlySegment: "B7vZc",
      yearlyLabel: "dh3yZ",
      savingsPill: "GViRF",
      planGrid: "c2Q5YO",
      planRowA: "FPR3D",
      planRowB: "gXihj",
      starterCard: "nk6hC",
      starterCardTop: "DVVQv",
      starterFeatures: "Esfie",
      starterAction: "i2Cet",
      growthCard: "CooOM",
      growthCardTop: "DDtk2",
      growthFeatures: "e9RTc",
      growthAction: "zXxnK",
      growthFootnote: "ckHEc",
      scaleCard: "rlOnA",
      scaleCardTop: "vifU4",
      scaleFeatures: "LVVdn",
      scaleAction: "hC7fB",
      enterpriseCard: "XLlvv",
      enterpriseCardTop: "L5UCrc",
      enterpriseFeatures: "T03RMP",
      enterpriseAction: "yE3Iy",
    },
  },
  {
    key: "blogTemplate",
    frameId: "k3CsMQ",
    titleId: "NajpK",
    descId: "nxCip",
    variantsId: "k3CsMQ",
    nodeIds: {},
  },
  {
    key: "docsTemplate",
    frameId: "XprWd",
    titleId: "R12dN",
    descId: "epBvD",
    variantsId: "XprWd",
    nodeIds: {},
  },
  {
    key: "onboardingTemplate",
    frameId: "Jl5uy",
    titleId: "fgcP9",
    descId: "XK8rG",
    variantsId: "Jl5uy",
    nodeIds: {},
  },
];
