/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import inputsMetadata from "@design/inputs-metadata.json";

import { CurrencyInputDemo } from "@/components/demos/CurrencyInputDemo";

const meta = inputsMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { CurrencyInput, formatCurrency } from "@gunjo/ui"

export function Example() {
  const [amount, setAmount] = React.useState<number | undefined>(1200000)
  return (
    <CurrencyInput value={amount} onValueChange={setAmount} min={0} />
    // value is a number; display elsewhere with formatCurrency(amount)
  )
}`;

const propsData = [
    { name: "value", type: "number", description: "Numeric amount (controlled)." },
    { name: "onValueChange", type: "(value: number | undefined) => void", description: "Fires with the number, or undefined when cleared." },
    { name: "currency", type: "string", default: "\"JPY\"", description: "ISO 4217 code for the symbol + grouping." },
    { name: "locale", type: "string", default: "\"ja-JP\"", description: "BCP-47 locale for the symbol + grouping." },
    { name: "showSymbol", type: "boolean", default: "true", description: "Show the currency symbol as a leading adornment." },
    { name: "min / max", type: "number", description: "Clamp the entered value." },
    { name: "...InputHTMLAttributes", type: "—", description: "id, name, placeholder, disabled, aria-*, className, etc." },
];

export default function CurrencyInputDocPage() {
    const title = meta.currencyInput.title ?? "CurrencyInput";
    const description = meta.currencyInput.description ?? "";

    return (
        <ComponentLayout title={title} description={description}>
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <CurrencyInputDemo />
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
        </ComponentLayout>
    );
}
