/**
 * Generated by `npm run design:sync:docs-pages`.
 * Generated docs component page scaffold from metadata + component-specs.
 */
"use client";

import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { ComponentDemoStates } from "@/components/doc/ComponentDemoStates";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import { useLocale } from "@/components/providers/LocaleProvider";
import patternsMetadata from "@design/patterns-metadata.json";

import * as React from "react";
import { ResponsiveAuthCardPattern } from "@gunjo/ui";

const PreviewComponent = ResponsiveAuthCardPattern as React.ComponentType<Record<string, unknown>>;

const usageCode = "import { ResponsiveAuthCardPattern } from \"@gunjo/ui\"\n\nexport function Example() {\n  return <ResponsiveAuthCardPattern />\n}";

const propsData = [
  {
    name: "brandName",
    type: "React.ReactNode",
    default: '"Gunjo Studio"',
    description: "Product or workspace name shown above the card.",
  },
  {
    name: "description",
    type: "React.ReactNode",
    description: "Line under the brand name that explains what the card is for.",
  },
  {
    name: "defaultMode",
    type: '"sign-in" | "create"',
    default: '"sign-in"',
    description: "Which tab is active when the card first renders.",
  },
  {
    name: "signInTitle",
    type: "React.ReactNode",
    description: "Card title on the sign-in tab.",
  },
  {
    name: "signInDescription",
    type: "React.ReactNode",
    description: "Card description on the sign-in tab.",
  },
  {
    name: "createTitle",
    type: "React.ReactNode",
    description: "Card title on the create-account tab.",
  },
  {
    name: "createDescription",
    type: "React.ReactNode",
    description: "Card description on the create-account tab.",
  },
  {
    name: "termsHref",
    type: "string",
    default: '"#"',
    description: "Destination for the terms-of-service link under the create-account form.",
  },
  {
    name: "privacyHref",
    type: "string",
    default: '"#"',
    description: "Destination for the privacy-policy link under the create-account form.",
  },
  {
    name: "forgotPasswordHref",
    type: "string",
    default: '"#"',
    description: "Destination for the forgot-password link on the sign-in tab.",
  },
  {
    name: "labels",
    type: "Partial<ResponsiveAuthCardPatternLabels>",
    description: "Every string in the card — tabs, field labels, placeholders, password rules, and validation messages. Defaults are Japanese, so pass this to run the card in another language.",
  },
  {
    name: "onSignIn",
    type: "(values: ResponsiveAuthCardPatternSignInValues) => void",
    description: "Called with { email, password, remember } once the sign-in form passes validation.",
  },
  {
    name: "onCreateAccount",
    type: "(values: ResponsiveAuthCardPatternCreateAccountValues) => void",
    description: "Called with { name, email, password } once the create-account form passes validation.",
  },
  {
    name: "className",
    type: "string",
    description: "Additional CSS class names.",
  },
];

const EN_LABELS = {
  signInTab: "Sign in",
  createTab: "Create account",
  emailLabel: "Email",
  passwordLabel: "Password",
  nameLabel: "Name",
  confirmLabel: "Confirm password",
  rememberLabel: "Remember this device",
  rememberAriaLabel: "Remember this device",
  forgotPassword: "Forgot your password?",
  signInButton: "Sign in",
  createButton: "Create account",
  passwordHint: "At least 8 characters, with upper and lower case letters and a number.",
  termsPrefix: "By continuing you agree to our ",
  terms: "terms of service",
  and: " and ",
  privacy: "privacy policy",
  termsSuffix: ".",
  emailPlaceholder: "you@example.com",
  passwordPlaceholder: "Enter your password",
  namePlaceholder: "Misaki Tanaka",
  createPasswordPlaceholder: "Create a password",
  confirmPlaceholder: "Re-enter your password",
  passwordRequirementLength: "At least 8 characters",
  passwordRequirementCase: "Upper and lower case letters",
  passwordRequirementNumber: "Contains a number",
  validation: {
    emailRequired: "Enter your email address.",
    emailInvalid: "Enter a valid email address.",
    passwordRequired: "Enter your password.",
    nameRequired: "Enter your name.",
    passwordWeak: "This password does not meet the requirements.",
    passwordMismatch: "The passwords do not match.",
  },
};

export default function ResponsiveAuthCardPatternDocPage() {
  const { locale } = useLocale();
  const localeProps = locale === "ja"
    ? {}
    : {
      brandName: "Gunjo Studio",
      description: "Sign in or create an account to continue.",
      signInTitle: "Welcome back",
      signInDescription: "Sign in to reach your workspace.",
      createTitle: "Create an account",
      createDescription: "Fill in your details to start a workspace.",
      labels: EN_LABELS,
    };

  return (
    <ComponentLayout
      title={patternsMetadata.responsiveAuthCardPattern.title}
      description={patternsMetadata.responsiveAuthCardPattern.description}
      usedComponents={[
        { name: "Card", href: "/docs/components/card" },
        { name: "Tabs", href: "/docs/components/tabs" },
        { name: "Form", href: "/docs/components/form" },
        { name: "Input", href: "/docs/components/input" },
        { name: "PasswordInput", href: "/docs/components/password-input" },
        { name: "PasswordRequirementList", href: "/docs/components/password-requirement-list" },
        { name: "Checkbox", href: "/docs/components/checkbox" },
        { name: "Button", href: "/docs/components/button" },
        { name: "TextLink", href: "/docs/components/text-link" },
      ]}
      relatedComponents={[
        { name: "AuthTemplate", href: "/docs/components/auth" },
        { name: "OnboardingTemplate", href: "/docs/components/onboarding" },
        { name: "PasswordStrengthMeter", href: "/docs/components/password-strength-meter" },
        { name: "PasswordGroup", href: "/docs/components/password-group" },
      ]}
    >
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <PreviewComponent />
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0" id="states">
          {locale === "ja" ? "状態とバリエーション" : "States and variants"}
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {locale === "ja"
            ? "defaultMode がどちらの札で開くかを決め、labels がカードの文字を丸ごと差し替えます。規約と再設定のリンク先は termsHref・privacyHref・forgotPasswordHref で指します。"
            : "defaultMode picks the tab it opens on, labels replaces every string in the card, and termsHref, privacyHref, and forgotPasswordHref point the legal and recovery links somewhere real."}
        </p>
        <ComponentDemoStates
          states={[
            {
              key: "create-first",
              title: locale === "ja" ? "作成の札で開く" : "Opens on create account",
              description: locale === "ja"
                ? "defaultMode=\"create\" を渡すと、アカウント作成の札が選ばれた状態で出ます。招待のリンクから来た人に見せる形です。"
                : "With defaultMode=\"create\" the card opens on the create-account tab. This is what someone arriving from an invitation should land on.",
              preview: (
                <ResponsiveAuthCardPattern
                  className="min-h-0"
                  defaultMode="create"
                  {...localeProps}
                />
              ),
              code: locale === "ja"
                ? `import { ResponsiveAuthCardPattern } from "@gunjo/ui";

export function CreateAccountFirst() {
  return <ResponsiveAuthCardPattern className="min-h-0" defaultMode="create" />;
}`
                : `import { ResponsiveAuthCardPattern } from "@gunjo/ui";

const EN_LABELS = {
  signInTab: "Sign in",
  createTab: "Create account",
  emailLabel: "Email",
  passwordLabel: "Password",
  nameLabel: "Name",
  confirmLabel: "Confirm password",
  signInButton: "Sign in",
  createButton: "Create account",
};

export function CreateAccountFirst() {
  return (
    <ResponsiveAuthCardPattern
      className="min-h-0"
      defaultMode="create"
      labels={EN_LABELS}
      brandName="Gunjo Studio"
      description="Sign in or create an account to continue."
      createTitle="Create an account"
      createDescription="Fill in your details to start a workspace."
    />
  );
}`,
            },
            {
              key: "reworded",
              title: locale === "ja" ? "文字を丸ごと差し替える" : "Rewording the whole card",
              description: locale === "ja"
                ? "組み込みの文字は日本語です。別の言い回しや別の言語で出すときは labels に渡します。渡した分だけが上書きされます。"
                : "The built-in strings are Japanese, so labels is how you run this card in another language. Only the keys you pass are overridden.",
              preview: (
                <ResponsiveAuthCardPattern
                  className="min-h-0"
                  brandName={locale === "ja" ? "群青 会員証" : "Gunjo Membership"}
                  description={locale === "ja" ? "会員証の発行と再発行はこちらです。" : "Issue or replace your membership card here."}
                  signInTitle={locale === "ja" ? "会員証をお持ちの方" : "Already a member"}
                  signInDescription={locale === "ja" ? "登録済みのメールアドレスでお入りください。" : "Use the email address you registered with."}
                  createTitle={locale === "ja" ? "はじめての方" : "New here"}
                  createDescription={locale === "ja" ? "1分で会員証を発行できます。" : "Getting a card takes about a minute."}
                  labels={locale === "ja"
                    ? { signInTab: "会員証で入る", createTab: "会員証を作る", signInButton: "入る", createButton: "会員証を作る" }
                    : { ...EN_LABELS, signInTab: "Use my card", createTab: "Get a card", signInButton: "Enter", createButton: "Get a card" }}
                />
              ),
              code: locale === "ja"
                ? `import { ResponsiveAuthCardPattern } from "@gunjo/ui";

const LABELS = {
  signInTab: "会員証で入る",
  createTab: "会員証を作る",
  signInButton: "入る",
  createButton: "会員証を作る",
};

export function RewordedAuthCard() {
  return (
    <ResponsiveAuthCardPattern
      className="min-h-0"
      brandName="群青 会員証"
      description="会員証の発行と再発行はこちらです。"
      signInTitle="会員証をお持ちの方"
      signInDescription="登録済みのメールアドレスでお入りください。"
      createTitle="はじめての方"
      createDescription="1分で会員証を発行できます。"
      labels={LABELS}
    />
  );
}`
                : `import { ResponsiveAuthCardPattern } from "@gunjo/ui";

const LABELS = {
  signInTab: "Use my card",
  createTab: "Get a card",
  emailLabel: "Email",
  passwordLabel: "Password",
  nameLabel: "Name",
  confirmLabel: "Confirm password",
  signInButton: "Enter",
  createButton: "Get a card",
};

export function RewordedAuthCard() {
  return (
    <ResponsiveAuthCardPattern
      className="min-h-0"
      brandName="Gunjo Membership"
      description="Issue or replace your membership card here."
      signInTitle="Already a member"
      signInDescription="Use the email address you registered with."
      createTitle="New here"
      createDescription="Getting a card takes about a minute."
      labels={LABELS}
    />
  );
}`,
            },
            {
              key: "real-links",
              title: locale === "ja" ? "リンク先を実在の頁に向ける" : "Pointing the links somewhere real",
              description: locale === "ja"
                ? "termsHref・privacyHref・forgotPasswordHref の既定は \"#\" です。公開する前に、規約・方針・再設定の頁へ向け直します。"
                : "termsHref, privacyHref, and forgotPasswordHref all default to \"#\". Point them at your real terms, policy, and password-reset pages before shipping.",
              preview: (
                <ResponsiveAuthCardPattern
                  className="min-h-0"
                  defaultMode="create"
                  termsHref="/docs/introduction"
                  privacyHref="/docs/introduction"
                  forgotPasswordHref="/docs/introduction"
                  {...localeProps}
                />
              ),
              code: locale === "ja"
                ? `import { ResponsiveAuthCardPattern } from "@gunjo/ui";

export function AuthCardWithRealLinks() {
  return (
    <ResponsiveAuthCardPattern
      className="min-h-0"
      defaultMode="create"
      termsHref="/legal/terms"
      privacyHref="/legal/privacy"
      forgotPasswordHref="/account/reset"
    />
  );
}`
                : `import { ResponsiveAuthCardPattern } from "@gunjo/ui";

const EN_LABELS = {
  signInTab: "Sign in",
  createTab: "Create account",
  emailLabel: "Email",
  passwordLabel: "Password",
  nameLabel: "Name",
  confirmLabel: "Confirm password",
  signInButton: "Sign in",
  createButton: "Create account",
};

export function AuthCardWithRealLinks() {
  return (
    <ResponsiveAuthCardPattern
      className="min-h-0"
      defaultMode="create"
      labels={EN_LABELS}
      termsHref="/legal/terms"
      privacyHref="/legal/privacy"
      forgotPasswordHref="/account/reset"
    />
  );
}`,
            },
          ]}
        />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
