/**
 * Generated by `npm run design:sync:docs-pages`.
 * Generated docs component page scaffold from metadata + component-specs.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import patternsMetadata from "@design/patterns-metadata.json";

import * as React from "react";
import { ResponsiveAuthCardPattern } from "@gunjo/ui";

const PreviewComponent = ResponsiveAuthCardPattern as React.ComponentType<Record<string, unknown>>;

const usageCode = "import { ResponsiveAuthCardPattern } from \"@gunjo/ui\"\n\nexport function Example() {\n  return <ResponsiveAuthCardPattern />\n}";

const propsData = [
  {
    name: "className",
    type: "string",
    description: "Additional CSS class names.",
  },

];

export default function ResponsiveAuthCardPatternDocPage() {
  return (
    <ComponentLayout
      title={patternsMetadata.responsiveAuthCardPattern.title}
      description={patternsMetadata.responsiveAuthCardPattern.description}
    >
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <PreviewComponent />
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
