// Generated by `npm run design:sync:seo-layouts`. Do not edit manually.
import type { ReactNode } from "react";
import type { Metadata } from "next";
import { pageMetadata } from "@/lib/seo/page-metadata";
import { StructuredData } from "@/components/seo/StructuredData";

export const metadata: Metadata = pageMetadata("/docs/components/desktop-page-header");

export default function SeoLayout({ children }: { children: ReactNode }) {
    return (
        <>
            <StructuredData path="/docs/components/desktop-page-header" />
            {children}
        </>
    );
}
