/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { Rating } from "@gunjo/ui";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { Rating } from "@gunjo/ui"

export function Example() {
  return <Rating value={4.5} reviewCount={128} showValue />
}`;

const propsData = [
  { name: "value", type: "number", description: "Current rating (e.g. 4.5). Rounded to the nearest half-star." },
  { name: "max", type: "number", default: "5", description: "Maximum number of stars." },
  { name: "size", type: "\"sm\" | \"default\" | \"lg\"", default: "\"default\"", description: "Star size." },
  { name: "reviewCount", type: "number", description: "Optional review count rendered after the stars." },
  { name: "showValue", type: "boolean", description: "Render the numeric value before the stars." },
  { name: "label", type: "string", description: "Override the accessible label (default \"{value} out of {max} stars\")." },
  { name: "className", type: "string", description: "Additional CSS class names." },
];

export default function RatingDocPage() {
  const title = meta.rating.title ?? "Rating";
  const description = meta.rating.description ?? "";

  return (
    <ComponentLayout title={title} description={description}>
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <div className="flex flex-col items-center gap-3">
          <Rating value={4.5} reviewCount={128} showValue />
          <Rating value={3} size="sm" />
          <Rating value={5} size="lg" />
        </div>
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
