"use client";

/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { ComponentDemoStates } from "@/components/doc/ComponentDemoStates";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import { useLocale } from "@/components/providers/LocaleProvider";
import displayMetadata from "@design/display-metadata.json";

import { Rating } from "@gunjo/ui";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { Rating } from "@gunjo/ui"

export function Example() {
  return <Rating value={4.5} reviewCount={128} showValue />
}`;

const propsData = [
  { name: "value", type: "number", description: "Current rating (e.g. 4.5). Rounded to the nearest half-star." },
  { name: "max", type: "number", default: "5", description: "Maximum number of stars." },
  { name: "size", type: "\"sm\" | \"default\" | \"lg\"", default: "\"default\"", description: "Star size." },
  { name: "reviewCount", type: "number", description: "Optional review count rendered after the stars." },
  { name: "showValue", type: "boolean", description: "Render the numeric value before the stars." },
  { name: "label", type: "string", description: "Override the accessible label (default \"{value} out of {max} stars\")." },
  { name: "className", type: "string", description: "Additional CSS class names." },
];

export default function RatingDocPage() {
  const { locale } = useLocale();
  const title = meta.rating.title ?? "Rating";
  const description = meta.rating.description ?? "";

  return (
    <ComponentLayout
      title={title}
      description={description}
      usedComponents={[]}
      relatedComponents={[
        { name: "DistributionBar", href: "/docs/components/distribution-bar" },
        { name: "Statistic", href: "/docs/components/statistic" },
        { name: "Meter", href: "/docs/components/meter" },
      ]}
    >
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <div className="flex flex-col items-center gap-3">
          <Rating value={4.5} reviewCount={128} showValue />
          <Rating value={3} size="sm" />
          <Rating value={5} size="lg" />
        </div>
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0" id="states">
          {locale === "ja" ? "状態とバリエーション" : "States and variants"}
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {locale === "ja"
            ? "Rating は読み取り専用の表示で、星は装飾です。意味は role=\"img\" に付いた1本の名前だけが担うので、星の数（max）を変えたときも、評価がまだ無いときも、その名前が正しいかどうかが要になります。名前は label で差し替えます。"
            : "Rating is read-only, and the stars themselves are decorative. All the meaning rides on one accessible name attached to a role=\"img\" wrapper, so whenever the scale changes or there is nothing to score yet, that name is the thing to get right. label is how you replace it."}
        </p>
        <ComponentDemoStates
          states={[
            {
              key: "scale",
              title: locale === "ja" ? "5段階以外の目盛り" : "Scales other than five",
              description: locale === "ja"
                ? "max は星の本数を決めます。10段階の満足度や3段階の難易度のように、5でない目盛りをそのまま出せます。value は半分単位に丸められるので、7.5 は星7つ半になります。"
                : "max sets how many stars are drawn, so a ten-point satisfaction score or a three-point difficulty scale renders as itself. value is rounded to the nearest half, which is why 7.5 lands on seven and a half stars.",
              preview: (
                <div className="flex flex-col gap-3">
                  <Rating value={7.5} max={10} showValue />
                  <Rating value={2.5} max={3} showValue />
                </div>
              ),
              code: `import { Rating } from "@gunjo/ui";

export function SurveyScores() {
  return (
    <div className="flex flex-col gap-3">
      <Rating value={7.5} max={10} showValue />
      <Rating value={2.5} max={3} showValue />
    </div>
  );
}`,
            },
            {
              key: "accessible-name",
              title: locale === "ja" ? "読み上げの名前を差し替える" : "Replacing the announced name",
              description: locale === "ja"
                ? "label を渡さないときの名前は英語の \"4.5 out of 5 stars\" です。日本語の画面ではここが英語のまま残るので、label で書き換えます。画面の見た目は変わらず、読み上げだけが変わります。"
                : "Without label, the announced name is the built-in \"4.5 out of 5 stars\". Replace it when the surrounding copy has more to say than the bare number, such as naming what is being scored. Nothing on screen changes; only what is announced does.",
              preview: (
                <Rating
                  value={4.5}
                  reviewCount={128}
                  showValue
                  label={locale === "ja"
                    ? "5段階中 4.5、レビュー128件"
                    : "Rated 4.5 out of 5 from 128 reviews"}
                />
              ),
              code: locale === "ja"
                ? `import { Rating } from "@gunjo/ui";

export function ProductScore() {
  return (
    <Rating
      value={4.5}
      reviewCount={128}
      showValue
      label="5段階中 4.5、レビュー128件"
    />
  );
}`
                : `import { Rating } from "@gunjo/ui";

export function ProductScore() {
  return (
    <Rating
      value={4.5}
      reviewCount={128}
      showValue
      label="Rated 4.5 out of 5 from 128 reviews"
    />
  );
}`,
            },
            {
              key: "no-reviews",
              title: locale === "ja" ? "評価がまだ無いとき" : "Nothing has been rated yet",
              description: locale === "ja"
                ? "件数が0のときに value=0 をそのまま出すと、星が全部空の「最低評価」に見えます。0件は評価ではないので、星の横に文字を添え、label もその文字に合わせます。"
                : "Passing value=0 when there are no reviews reads as the worst possible score rather than the absence of one. Say so in words next to the stars, and point label at the same words.",
              preview: (
                <div className="flex items-center gap-2">
                  <Rating
                    value={0}
                    label={locale === "ja" ? "レビューはまだありません" : "No reviews yet"}
                  />
                  <span className="text-sm text-muted-foreground">
                    {locale === "ja" ? "レビューはまだありません" : "No reviews yet"}
                  </span>
                </div>
              ),
              code: locale === "ja"
                ? `import { Rating } from "@gunjo/ui";

const reviews: number[] = [];

export function ProductRating() {
  if (reviews.length === 0) {
    return (
      <div className="flex items-center gap-2">
        <Rating value={0} label="レビューはまだありません" />
        <span className="text-sm text-muted-foreground">
          レビューはまだありません
        </span>
      </div>
    );
  }

  const total = reviews.reduce((sum, score) => sum + score, 0);
  return (
    <Rating
      value={total / reviews.length}
      reviewCount={reviews.length}
      showValue
    />
  );
}`
                : `import { Rating } from "@gunjo/ui";

const reviews: number[] = [];

export function ProductRating() {
  if (reviews.length === 0) {
    return (
      <div className="flex items-center gap-2">
        <Rating value={0} label="No reviews yet" />
        <span className="text-sm text-muted-foreground">
          No reviews yet
        </span>
      </div>
    );
  }

  const total = reviews.reduce((sum, score) => sum + score, 0);
  return (
    <Rating
      value={total / reviews.length}
      reviewCount={reviews.length}
      showValue
    />
  );
}`,
            },
          ]}
        />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
