/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { ApprovalStepsDemo } from "@/components/demos/ApprovalStepsDemo";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui"

const steps: ApprovalStep[] = [
  { label: "申請", state: "approved", actor: "山田 太郎", timestamp: "5/20 10:12" },
  { label: "一次承認（上長）", state: "rejected", actor: "佐藤 部長",
    timestamp: "5/20 14:40", comment: "勘定科目を会議費に修正のうえ再申請してください。" },
  { label: "経理確認", state: "current", actor: "経理部" },
  { label: "支払", state: "pending" },
]

export function Example() {
  return (
    <ApprovalSteps steps={steps}
      stateLabels={{ approved: "承認", rejected: "差戻し", current: "確認中", pending: "待ち" }} />
  )
}`;

const propsData = [
    { name: "steps", type: "ApprovalStep[]", description: "Each step: { label, state, actor?, timestamp?, comment? }." },
    { name: "state (per step)", type: "\"pending\" | \"current\" | \"approved\" | \"rejected\" | \"skipped\"", description: "Maps to a marker tone, icon, and text label (state is never colour-only)." },
    { name: "stateLabels", type: "Partial<Record<state, string>>", description: "Localizable state text (also used in each step's aria-label)." },
    { name: "variant", type: "\"default\" | \"compact\"", default: "\"default\"", description: "Density." },
    { name: "className", type: "string", description: "Additional CSS class names." },
];

export default function ApprovalStepsDocPage() {
    const title = meta.approvalSteps.title ?? "ApprovalSteps";
    const description = meta.approvalSteps.description ?? "";

    return (
        <ComponentLayout title={title} description={description}>
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <ApprovalStepsDemo />
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
        </ComponentLayout>
    );
}
