"use client";

/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui";
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { ComponentDemoStates } from "@/components/doc/ComponentDemoStates";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import { useLocale } from "@/components/providers/LocaleProvider";
import displayMetadata from "@design/display-metadata.json";

import { ApprovalStepsDemo } from "@/components/demos/ApprovalStepsDemo";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui"

const steps: ApprovalStep[] = [
  { label: "申請", state: "approved", actor: "山田 太郎", timestamp: "5/20 10:12" },
  { label: "一次承認（上長）", state: "rejected", actor: "佐藤 部長",
    timestamp: "5/20 14:40", comment: "勘定科目を会議費に修正のうえ再申請してください。" },
  { label: "経理確認", state: "current", actor: "経理部" },
  { label: "支払", state: "pending" },
]

export function Example() {
  return (
    <ApprovalSteps steps={steps}
      stateLabels={{ approved: "承認", rejected: "差戻し", current: "確認中", pending: "待ち" }} />
  )
}`;

const propsData = [
    { name: "steps", type: "ApprovalStep[]", description: "Each step: { label, state, actor?, timestamp?, comment? }." },
    { name: "state (per step)", type: "\"pending\" | \"current\" | \"approved\" | \"rejected\" | \"skipped\"", description: "Maps to a marker tone, icon, and text label (state is never colour-only)." },
    { name: "stateLabels", type: "Partial<Record<state, string>>", description: "Localizable state text (also used in each step's aria-label)." },
    { name: "variant", type: "\"default\" | \"compact\"", default: "\"default\"", description: "Density." },
    { name: "className", type: "string", description: "Additional CSS class names." },
];

export default function ApprovalStepsDocPage() {
    const { locale } = useLocale();
    const title = meta.approvalSteps.title ?? "ApprovalSteps";
    const description = meta.approvalSteps.description ?? "";

    const beforeSubmitSteps: ApprovalStep[] = locale === "ja"
        ? [
            { label: "申請", state: "pending" },
            { label: "一次承認（上長）", state: "pending" },
            { label: "経理確認", state: "pending" },
            { label: "支払", state: "pending" },
        ]
        : [
            { label: "Submit", state: "pending" },
            { label: "Manager approval", state: "pending" },
            { label: "Finance check", state: "pending" },
            { label: "Payment", state: "pending" },
        ];

    const skippedSteps: ApprovalStep[] = locale === "ja"
        ? [
            { label: "申請", state: "approved", actor: "山田 太郎", timestamp: "6/2 09:40" },
            { label: "一次承認（上長）", state: "skipped", actor: "3万円未満のため省略" },
            { label: "経理確認", state: "current", actor: "経理部" },
            { label: "支払", state: "pending" },
        ]
        : [
            { label: "Submit", state: "approved", actor: "Taro Yamada", timestamp: "Jun 2, 09:40" },
            { label: "Manager approval", state: "skipped", actor: "Skipped: under 30,000 yen" },
            { label: "Finance check", state: "current", actor: "Finance" },
            { label: "Payment", state: "pending" },
        ];

    const compactSteps: ApprovalStep[] = locale === "ja"
        ? [
            { label: "申請", state: "approved", actor: "山田 太郎" },
            { label: "一次承認（上長）", state: "approved", actor: "佐藤 部長" },
            { label: "経理確認", state: "current", actor: "経理部" },
            { label: "支払", state: "pending" },
        ]
        : [
            { label: "Submit", state: "approved", actor: "Taro Yamada" },
            { label: "Manager approval", state: "approved", actor: "Sato (manager)" },
            { label: "Finance check", state: "current", actor: "Finance" },
            { label: "Payment", state: "pending" },
        ];

    return (
        <ComponentLayout
            title={title}
            description={description}
            usedComponents={[
                { name: "Timeline", href: "/docs/components/timeline" },
                { name: "TimelineItem", href: "/docs/components/timeline" },
                { name: "TimelineTitle", href: "/docs/components/timeline" },
                { name: "TimelineTime", href: "/docs/components/timeline" },
                { name: "TimelineDescription", href: "/docs/components/timeline" },
            ]}
            relatedComponents={[
                { name: "ApprovalWorkflow", href: "/docs/components/approval-workflow" },
                { name: "Timeline", href: "/docs/components/timeline" },
                { name: "Stepper", href: "/docs/components/stepper" },
                { name: "SignedRecord", href: "/docs/components/signed-record" },
            ]}
        >
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <ApprovalStepsDemo />
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0" id="states">
                    {locale === "ja" ? "状態とバリエーション" : "States and variants"}
                </h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                    {locale === "ja"
                        ? "経路の見え方は steps の各段の state と variant で決まります。state は印の色・アイコン・文字ラベルの3つを同時に切り替えるので、色が見えない人にも段の意味が伝わります。stateLabels は段の文字を差し替える口で、読み上げの文にも同じ文字が入ります。"
                        : "How a route reads comes from each step's state plus variant. A state switches the marker tone, the icon, and the text label together, so the meaning survives without colour. stateLabels replaces that text, and the same words go into the announced label."}
                </p>
                <ComponentDemoStates
                    states={[
                        {
                            key: "before-submit",
                            title: locale === "ja" ? "まだ誰も動いていない経路" : "A route nobody has touched",
                            description: locale === "ja"
                                ? "全部の段が pending のときは、これから誰の手を通るかだけが並びます。申請ボタンを押す前に経路を見せる画面がこれです。actor も timestamp も無いので、段の名前だけが残ります。"
                                : "With every step pending, the route shows only who it will pass through. This is the shape to put in front of someone before they submit: no actor, no timestamp, just the names of the steps.",
                            preview: (
                                <div className="w-full max-w-md">
                                    <ApprovalSteps
                                        steps={beforeSubmitSteps}
                                        stateLabels={locale === "ja" ? { pending: "これから" } : { pending: "Upcoming" }}
                                    />
                                </div>
                            ),
                            code: locale === "ja"
                                ? `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui";

const steps: ApprovalStep[] = [
  { label: "申請", state: "pending" },
  { label: "一次承認（上長）", state: "pending" },
  { label: "経理確認", state: "pending" },
  { label: "支払", state: "pending" },
];

export function RouteBeforeSubmit() {
  return (
    <ApprovalSteps steps={steps} stateLabels={{ pending: "これから" }} />
  );
}`
                                : `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui";

const steps: ApprovalStep[] = [
  { label: "Submit", state: "pending" },
  { label: "Manager approval", state: "pending" },
  { label: "Finance check", state: "pending" },
  { label: "Payment", state: "pending" },
];

export function RouteBeforeSubmit() {
  return (
    <ApprovalSteps steps={steps} stateLabels={{ pending: "Upcoming" }} />
  );
}`,
                        },
                        {
                            key: "skipped",
                            title: locale === "ja" ? "飛ばした段" : "A skipped step",
                            description: locale === "ja"
                                ? "金額が小さいなどの理由で承認が要らなかった段は skipped にします。消さずに残すのは、あとから経路を読む人に「省いた」と「まだ来ていない」を見分けてもらうためです。理由は actor に書けます。"
                                : "When a step was not required, because the amount was small or the approval was delegated, mark it skipped instead of dropping it. Keeping the rung visible is what lets a later reader tell a skipped step apart from one that has not happened yet. The reason goes in actor.",
                            preview: (
                                <div className="w-full max-w-md">
                                    <ApprovalSteps
                                        steps={skippedSteps}
                                        stateLabels={locale === "ja"
                                            ? { approved: "承認", skipped: "省略", current: "確認中", pending: "待ち" }
                                            : { approved: "Approved", skipped: "Skipped", current: "In review", pending: "Waiting" }}
                                    />
                                </div>
                            ),
                            code: locale === "ja"
                                ? `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui";

const steps: ApprovalStep[] = [
  { label: "申請", state: "approved", actor: "山田 太郎", timestamp: "6/2 09:40" },
  { label: "一次承認（上長）", state: "skipped", actor: "3万円未満のため省略" },
  { label: "経理確認", state: "current", actor: "経理部" },
  { label: "支払", state: "pending" },
];

export function SkippedStepRoute() {
  return (
    <ApprovalSteps
      steps={steps}
      stateLabels={{
        approved: "承認",
        skipped: "省略",
        current: "確認中",
        pending: "待ち",
      }}
    />
  );
}`
                                : `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui";

const steps: ApprovalStep[] = [
  { label: "Submit", state: "approved", actor: "Taro Yamada", timestamp: "Jun 2, 09:40" },
  { label: "Manager approval", state: "skipped", actor: "Skipped: under 30,000 yen" },
  { label: "Finance check", state: "current", actor: "Finance" },
  { label: "Payment", state: "pending" },
];

export function SkippedStepRoute() {
  return (
    <ApprovalSteps
      steps={steps}
      stateLabels={{
        approved: "Approved",
        skipped: "Skipped",
        current: "In review",
        pending: "Waiting",
      }}
    />
  );
}`,
                        },
                        {
                            key: "compact",
                            title: locale === "ja" ? "密度を上げる" : "Tighter density",
                            description: locale === "ja"
                                ? "variant=\"compact\" は文字を一段小さくします。経路が主役ではなく、明細の脇や一覧の行の中に添えるときに使います。段の数が多い経路でも縦に伸びすぎません。"
                                : "variant=\"compact\" drops the type down one step. Reach for it when the route is not the subject of the screen, such as beside an expense detail or inside a list row, so a long route does not run down the page.",
                            preview: (
                                <div className="w-full max-w-md">
                                    <ApprovalSteps
                                        variant="compact"
                                        steps={compactSteps}
                                        stateLabels={locale === "ja"
                                            ? { approved: "承認", current: "確認中", pending: "待ち" }
                                            : { approved: "Approved", current: "In review", pending: "Waiting" }}
                                    />
                                </div>
                            ),
                            code: locale === "ja"
                                ? `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui";

const steps: ApprovalStep[] = [
  { label: "申請", state: "approved", actor: "山田 太郎" },
  { label: "一次承認（上長）", state: "approved", actor: "佐藤 部長" },
  { label: "経理確認", state: "current", actor: "経理部" },
  { label: "支払", state: "pending" },
];

export function CompactRoute() {
  return (
    <ApprovalSteps
      variant="compact"
      steps={steps}
      stateLabels={{ approved: "承認", current: "確認中", pending: "待ち" }}
    />
  );
}`
                                : `import { ApprovalSteps, type ApprovalStep } from "@gunjo/ui";

const steps: ApprovalStep[] = [
  { label: "Submit", state: "approved", actor: "Taro Yamada" },
  { label: "Manager approval", state: "approved", actor: "Sato (manager)" },
  { label: "Finance check", state: "current", actor: "Finance" },
  { label: "Payment", state: "pending" },
];

export function CompactRoute() {
  return (
    <ApprovalSteps
      variant="compact"
      steps={steps}
      stateLabels={{ approved: "Approved", current: "In review", pending: "Waiting" }}
    />
  );
}`,
                        },
                    ]}
                />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
        </ComponentLayout>
    );
}
