/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { RevealSectionDemo } from "@/components/demos/RevealSectionDemo";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { RevealSection, Switch } from "@gunjo/ui"

export function Example() {
  const [hasSpouse, setHasSpouse] = React.useState(false)
  return (
    <>
      <Switch checked={hasSpouse} onCheckedChange={setHasSpouse} aria-label="配偶者あり" />
      <RevealSection open={hasSpouse} label="配偶者控除の申告">
        {/* fields revealed (and announced) when hasSpouse is true */}
      </RevealSection>
    </>
  )
}`;

const propsData = [
    { name: "open", type: "boolean", description: "Whether the section is shown. When false, nothing renders." },
    { name: "label", type: "string", description: "Accessible name for the revealed region (or pass aria-labelledby)." },
    { name: "announce", type: "boolean", default: "true", description: "Announce the section politely to screen readers when it appears." },
    { name: "...HTMLAttributes", type: "—", description: "className, aria-labelledby, etc." },
];

export default function RevealSectionDocPage() {
    const title = meta.revealSection.title ?? "RevealSection";
    const description = meta.revealSection.description ?? "";

    return (
        <ComponentLayout title={title} description={description}>
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <RevealSectionDemo />
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
        </ComponentLayout>
    );
}
