"use client";

/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import * as React from "react";
import { Checkbox, Input, Label, RevealSection, Switch, Textarea } from "@gunjo/ui";
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { ComponentDemoStates } from "@/components/doc/ComponentDemoStates";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import { useLocale } from "@/components/providers/LocaleProvider";
import displayMetadata from "@design/display-metadata.json";

import { RevealSectionDemo } from "@/components/demos/RevealSectionDemo";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { RevealSection, Switch } from "@gunjo/ui"

export function Example() {
  const [hasSpouse, setHasSpouse] = React.useState(false)
  return (
    <>
      <Switch checked={hasSpouse} onCheckedChange={setHasSpouse} aria-label="配偶者あり" />
      <RevealSection open={hasSpouse} label="配偶者控除の申告">
        {/* fields revealed (and announced) when hasSpouse is true */}
      </RevealSection>
    </>
  )
}`;

const propsData = [
    { name: "open", type: "boolean", description: "Whether the section is shown. When false, nothing renders." },
    { name: "label", type: "string", description: "Accessible name for the revealed region (or pass aria-labelledby)." },
    { name: "announce", type: "boolean", default: "true", description: "Announce the section politely to screen readers when it appears." },
    { name: "...HTMLAttributes", type: "—", description: "className, aria-labelledby, etc." },
];

function QuietRevealPreview({ locale }: { locale: "en" | "ja" }) {
    const [showNote, setShowNote] = React.useState(false);

    return (
        <div className="flex w-full max-w-md flex-col gap-3">
            <label className="flex items-center justify-between gap-3">
                <span className="text-sm font-medium text-foreground">
                    {locale === "ja" ? "計算の内訳を表示" : "Show how this was calculated"}
                </span>
                <Switch
                    checked={showNote}
                    onCheckedChange={setShowNote}
                    aria-label={locale === "ja" ? "計算の内訳を表示" : "Show how this was calculated"}
                />
            </label>

            <RevealSection
                open={showNote}
                announce={false}
                label={locale === "ja" ? "計算の内訳" : "Calculation breakdown"}
                className="rounded-md border bg-muted/30 p-4 text-sm text-muted-foreground"
            >
                {locale === "ja"
                    ? "課税所得 3,200,000 円 × 税率 10% − 控除額 97,500 円 = 222,500 円"
                    : "Taxable income 3,200,000 × rate 10% − deduction 97,500 = 222,500"}
            </RevealSection>
        </div>
    );
}

function LabelledByPreview({ locale }: { locale: "en" | "ja" }) {
    const [needsInvoice, setNeedsInvoice] = React.useState(true);

    return (
        <div className="flex w-full max-w-md flex-col gap-3">
            <label className="flex items-center justify-between gap-3">
                <span className="text-sm font-medium text-foreground">
                    {locale === "ja" ? "請求書の宛名を指定する" : "Set a billing name"}
                </span>
                <Switch
                    checked={needsInvoice}
                    onCheckedChange={setNeedsInvoice}
                    aria-label={locale === "ja" ? "請求書の宛名を指定する" : "Set a billing name"}
                />
            </label>

            <RevealSection
                open={needsInvoice}
                aria-labelledby="reveal-invoice-heading"
                className="rounded-md border bg-muted/30 p-4"
            >
                <h4 id="reveal-invoice-heading" className="mb-3 text-sm font-medium text-foreground">
                    {locale === "ja" ? "請求書の宛名" : "Billing name"}
                </h4>
                <div className="flex flex-col gap-2">
                    <Label htmlFor="reveal-invoice-name">
                        {locale === "ja" ? "会社名" : "Company"}
                    </Label>
                    <Input
                        id="reveal-invoice-name"
                        placeholder={locale === "ja" ? "株式会社 群青" : "Gunjo Inc."}
                    />
                </div>
            </RevealSection>
        </div>
    );
}

function ChainedRevealPreview({ locale }: { locale: "en" | "ja" }) {
    const [absent, setAbsent] = React.useState(false);
    const [leaveAtDoor, setLeaveAtDoor] = React.useState(false);

    return (
        <div className="flex w-full max-w-md flex-col gap-3">
            <div className="flex items-center gap-2">
                <Checkbox
                    id="reveal-absent"
                    checked={absent}
                    onCheckedChange={(next) => setAbsent(next === true)}
                />
                <Label htmlFor="reveal-absent">
                    {locale === "ja" ? "受け取りに出られないことがある" : "I may not be home to receive it"}
                </Label>
            </div>

            <RevealSection
                open={absent}
                label={locale === "ja" ? "不在時の扱い" : "If nobody is home"}
                className="flex flex-col gap-3 rounded-md border bg-muted/30 p-4"
            >
                <div className="flex items-center gap-2">
                    <Checkbox
                        id="reveal-leave"
                        checked={leaveAtDoor}
                        onCheckedChange={(next) => setLeaveAtDoor(next === true)}
                    />
                    <Label htmlFor="reveal-leave">
                        {locale === "ja" ? "玄関前に置いてよい" : "Leaving it at the door is fine"}
                    </Label>
                </div>

                <RevealSection
                    open={leaveAtDoor}
                    label={locale === "ja" ? "置き場所の指定" : "Where to leave it"}
                    className="flex flex-col gap-2"
                >
                    <Label htmlFor="reveal-place">
                        {locale === "ja" ? "置き場所" : "Drop-off spot"}
                    </Label>
                    <Textarea
                        id="reveal-place"
                        rows={2}
                        placeholder={locale === "ja"
                            ? "宅配ボックスが空いていればそこへ"
                            : "In the parcel box if one is free"}
                    />
                </RevealSection>
            </RevealSection>
        </div>
    );
}

export default function RevealSectionDocPage() {
    const { locale } = useLocale();
    const title = meta.revealSection.title ?? "RevealSection";
    const description = meta.revealSection.description ?? "";

    return (
        <ComponentLayout
            title={title}
            description={description}
            usedComponents={[]}
            relatedComponents={[
                { name: "Accordion", href: "/docs/components/accordion" },
                { name: "Form", href: "/docs/components/form" },
                { name: "Alert", href: "/docs/components/alert" },
                { name: "CollapsiblePanelToggle", href: "/docs/components/collapsible-panel-toggle" },
            ]}
        >
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <RevealSectionDemo />
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0" id="states">
                    {locale === "ja" ? "状態とバリエーション" : "States and variants"}
                </h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                    {locale === "ja"
                        ? "RevealSection が持つ口は open・label・announce の3つだけで、残りは素の div と同じ属性です。変わるのは見た目ではなく、出てきた節にどう名前を付け、それを読み上げに知らせるかどうかです。"
                        : "RevealSection has three of its own props, open, label and announce; everything else passes through to a plain div. What varies is not the look but how the revealed region gets its name, and whether its arrival is announced at all."}
                </p>
                <ComponentDemoStates
                    states={[
                        {
                            key: "quiet",
                            title: locale === "ja" ? "読み上げに知らせない出し入れ" : "A reveal that stays quiet",
                            description: locale === "ja"
                                ? "announce={false} にすると aria-live が外れます。新しく答えることが増えたわけではなく、いま見ている数字の内訳を開いただけ、という場面ではこちらです。名前（label）は残るので、あとから辿り着いたときには節として読めます。"
                                : "announce={false} drops the aria-live wiring. Use it when opening the section did not add anything to answer, such as unfolding the arithmetic behind a figure already on screen. The name stays, so the region still reads as a named section when reached later.",
                            preview: <QuietRevealPreview locale={locale} />,
                            code: locale === "ja"
                                ? `import * as React from "react";
import { RevealSection, Switch } from "@gunjo/ui";

export function CalculationNote() {
  const [showNote, setShowNote] = React.useState(false);

  return (
    <div className="flex flex-col gap-3">
      <label className="flex items-center justify-between gap-3">
        <span className="text-sm font-medium">計算の内訳を表示</span>
        <Switch
          checked={showNote}
          onCheckedChange={setShowNote}
          aria-label="計算の内訳を表示"
        />
      </label>

      <RevealSection
        open={showNote}
        announce={false}
        label="計算の内訳"
        className="rounded-md border bg-muted/30 p-4 text-sm"
      >
        課税所得 3,200,000 円 × 税率 10% − 控除額 97,500 円 = 222,500 円
      </RevealSection>
    </div>
  );
}`
                                : `import * as React from "react";
import { RevealSection, Switch } from "@gunjo/ui";

export function CalculationNote() {
  const [showNote, setShowNote] = React.useState(false);

  return (
    <div className="flex flex-col gap-3">
      <label className="flex items-center justify-between gap-3">
        <span className="text-sm font-medium">Show how this was calculated</span>
        <Switch
          checked={showNote}
          onCheckedChange={setShowNote}
          aria-label="Show how this was calculated"
        />
      </label>

      <RevealSection
        open={showNote}
        announce={false}
        label="Calculation breakdown"
        className="rounded-md border bg-muted/30 p-4 text-sm"
      >
        Taxable income 3,200,000 × rate 10% − deduction 97,500 = 222,500
      </RevealSection>
    </div>
  );
}`,
                        },
                        {
                            key: "labelled-by",
                            title: locale === "ja" ? "画面にある見出しを名前にする" : "Naming it with a heading already on screen",
                            description: locale === "ja"
                                ? "節の中に見出しを置くなら、label で同じ言葉をもう一度書くのではなく aria-labelledby でその見出しを指します。名前が2つに割れず、見出しの文言を直したときに読み上げも一緒に直ります。"
                                : "When the section contains its own heading, point aria-labelledby at it instead of repeating the words in label. The name then has a single source, and editing the heading updates what is announced.",
                            preview: <LabelledByPreview locale={locale} />,
                            code: locale === "ja"
                                ? `import * as React from "react";
import { Input, Label, RevealSection, Switch } from "@gunjo/ui";

export function BillingNameSection() {
  const [needsInvoice, setNeedsInvoice] = React.useState(true);

  return (
    <div className="flex flex-col gap-3">
      <label className="flex items-center justify-between gap-3">
        <span className="text-sm font-medium">請求書の宛名を指定する</span>
        <Switch
          checked={needsInvoice}
          onCheckedChange={setNeedsInvoice}
          aria-label="請求書の宛名を指定する"
        />
      </label>

      <RevealSection
        open={needsInvoice}
        aria-labelledby="invoice-heading"
        className="rounded-md border bg-muted/30 p-4"
      >
        <h4 id="invoice-heading" className="mb-3 text-sm font-medium">
          請求書の宛名
        </h4>
        <div className="flex flex-col gap-2">
          <Label htmlFor="invoice-name">会社名</Label>
          <Input id="invoice-name" placeholder="株式会社 群青" />
        </div>
      </RevealSection>
    </div>
  );
}`
                                : `import * as React from "react";
import { Input, Label, RevealSection, Switch } from "@gunjo/ui";

export function BillingNameSection() {
  const [needsInvoice, setNeedsInvoice] = React.useState(true);

  return (
    <div className="flex flex-col gap-3">
      <label className="flex items-center justify-between gap-3">
        <span className="text-sm font-medium">Set a billing name</span>
        <Switch
          checked={needsInvoice}
          onCheckedChange={setNeedsInvoice}
          aria-label="Set a billing name"
        />
      </label>

      <RevealSection
        open={needsInvoice}
        aria-labelledby="invoice-heading"
        className="rounded-md border bg-muted/30 p-4"
      >
        <h4 id="invoice-heading" className="mb-3 text-sm font-medium">
          Billing name
        </h4>
        <div className="flex flex-col gap-2">
          <Label htmlFor="invoice-name">Company</Label>
          <Input id="invoice-name" placeholder="Gunjo Inc." />
        </div>
      </RevealSection>
    </div>
  );
}`,
                        },
                        {
                            key: "chained",
                            title: locale === "ja" ? "答えが次の答えを開く" : "One answer opens the next",
                            description: locale === "ja"
                                ? "節の中にもう一段の節を置けます。open がそれぞれ別の答えを見ているので、最初のチェックを外せば内側も一緒に消えます。申告書や配送の指定のように、条件が枝分かれする入力はこの形になります。"
                                : "A section can hold another one. Each open watches a different answer, so clearing the first checkbox takes the inner section with it. Declaration forms and delivery options branch exactly like this.",
                            preview: <ChainedRevealPreview locale={locale} />,
                            code: locale === "ja"
                                ? `import * as React from "react";
import { Checkbox, Label, RevealSection, Textarea } from "@gunjo/ui";

export function DeliveryOptions() {
  const [absent, setAbsent] = React.useState(false);
  const [leaveAtDoor, setLeaveAtDoor] = React.useState(false);

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Checkbox
          id="absent"
          checked={absent}
          onCheckedChange={(next) => setAbsent(next === true)}
        />
        <Label htmlFor="absent">受け取りに出られないことがある</Label>
      </div>

      <RevealSection
        open={absent}
        label="不在時の扱い"
        className="flex flex-col gap-3 rounded-md border bg-muted/30 p-4"
      >
        <div className="flex items-center gap-2">
          <Checkbox
            id="leave"
            checked={leaveAtDoor}
            onCheckedChange={(next) => setLeaveAtDoor(next === true)}
          />
          <Label htmlFor="leave">玄関前に置いてよい</Label>
        </div>

        <RevealSection
          open={leaveAtDoor}
          label="置き場所の指定"
          className="flex flex-col gap-2"
        >
          <Label htmlFor="place">置き場所</Label>
          <Textarea id="place" rows={2} placeholder="宅配ボックスが空いていればそこへ" />
        </RevealSection>
      </RevealSection>
    </div>
  );
}`
                                : `import * as React from "react";
import { Checkbox, Label, RevealSection, Textarea } from "@gunjo/ui";

export function DeliveryOptions() {
  const [absent, setAbsent] = React.useState(false);
  const [leaveAtDoor, setLeaveAtDoor] = React.useState(false);

  return (
    <div className="flex flex-col gap-3">
      <div className="flex items-center gap-2">
        <Checkbox
          id="absent"
          checked={absent}
          onCheckedChange={(next) => setAbsent(next === true)}
        />
        <Label htmlFor="absent">I may not be home to receive it</Label>
      </div>

      <RevealSection
        open={absent}
        label="If nobody is home"
        className="flex flex-col gap-3 rounded-md border bg-muted/30 p-4"
      >
        <div className="flex items-center gap-2">
          <Checkbox
            id="leave"
            checked={leaveAtDoor}
            onCheckedChange={(next) => setLeaveAtDoor(next === true)}
          />
          <Label htmlFor="leave">Leaving it at the door is fine</Label>
        </div>

        <RevealSection
          open={leaveAtDoor}
          label="Where to leave it"
          className="flex flex-col gap-2"
        >
          <Label htmlFor="place">Drop-off spot</Label>
          <Textarea id="place" rows={2} placeholder="In the parcel box if one is free" />
        </RevealSection>
      </RevealSection>
    </div>
  );
}`,
                        },
                    ]}
                />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
        </ComponentLayout>
    );
}
