// AUTO-GENERATED by scripts/design-sync/sync-token-scales.mjs — do not edit.
// The spacing / type scale GunjoUI publishes, from scripts/design-sync/token-scales.mjs.
// /docs/spacing and /docs/typography read these instead of re-typing the numbers,
// and public/tokens.css ships the same scale as --space-* / --text-* for npm-less
// adopters. design:verify checks the scale against the installed Tailwind theme. (#969)

export type SpacingStep = {
    /** Tailwind step name, e.g. "4" or "0.5" or "px". */
    step: string;
    /** Standalone-sheet custom property, e.g. "--space-4". */
    token: string;
    /** Shipped value, e.g. "1rem". */
    value: string;
    /** What it measures at the 16px root default, e.g. "16px". */
    px: string;
    /** Tailwind width utility that draws this step. */
    widthClass: string;
};

export type TextStep = {
    utility: string;
    token: string;
    value: string;
    px: string;
};

export type ScaleStep = {
    utility: string;
    token: string;
    value: string;
};

export type FontStack = {
    token: string;
    value: string;
};

export type DensityToken = {
    token: string;
    value: string;
};

export const SPACING_SCALE: SpacingStep[] = [
    { step: "0", token: "--space-0", value: "0px", px: "0px", widthClass: "w-0" },
    { step: "px", token: "--space-px", value: "1px", px: "1px", widthClass: "w-px" },
    { step: "0.5", token: "--space-0-5", value: "0.125rem", px: "2px", widthClass: "w-0.5" },
    { step: "1", token: "--space-1", value: "0.25rem", px: "4px", widthClass: "w-1" },
    { step: "1.5", token: "--space-1-5", value: "0.375rem", px: "6px", widthClass: "w-1.5" },
    { step: "2", token: "--space-2", value: "0.5rem", px: "8px", widthClass: "w-2" },
    { step: "2.5", token: "--space-2-5", value: "0.625rem", px: "10px", widthClass: "w-2.5" },
    { step: "3", token: "--space-3", value: "0.75rem", px: "12px", widthClass: "w-3" },
    { step: "3.5", token: "--space-3-5", value: "0.875rem", px: "14px", widthClass: "w-3.5" },
    { step: "4", token: "--space-4", value: "1rem", px: "16px", widthClass: "w-4" },
    { step: "5", token: "--space-5", value: "1.25rem", px: "20px", widthClass: "w-5" },
    { step: "6", token: "--space-6", value: "1.5rem", px: "24px", widthClass: "w-6" },
    { step: "7", token: "--space-7", value: "1.75rem", px: "28px", widthClass: "w-7" },
    { step: "8", token: "--space-8", value: "2rem", px: "32px", widthClass: "w-8" },
    { step: "9", token: "--space-9", value: "2.25rem", px: "36px", widthClass: "w-9" },
    { step: "10", token: "--space-10", value: "2.5rem", px: "40px", widthClass: "w-10" },
    { step: "12", token: "--space-12", value: "3rem", px: "48px", widthClass: "w-12" },
    { step: "14", token: "--space-14", value: "3.5rem", px: "56px", widthClass: "w-14" },
    { step: "16", token: "--space-16", value: "4rem", px: "64px", widthClass: "w-16" },
    { step: "20", token: "--space-20", value: "5rem", px: "80px", widthClass: "w-20" },
    { step: "24", token: "--space-24", value: "6rem", px: "96px", widthClass: "w-24" },
    { step: "28", token: "--space-28", value: "7rem", px: "112px", widthClass: "w-28" },
    { step: "32", token: "--space-32", value: "8rem", px: "128px", widthClass: "w-32" },
    { step: "36", token: "--space-36", value: "9rem", px: "144px", widthClass: "w-36" },
    { step: "40", token: "--space-40", value: "10rem", px: "160px", widthClass: "w-40" },
    { step: "48", token: "--space-48", value: "12rem", px: "192px", widthClass: "w-48" },
    { step: "56", token: "--space-56", value: "14rem", px: "224px", widthClass: "w-56" },
    { step: "64", token: "--space-64", value: "16rem", px: "256px", widthClass: "w-64" },
];

export const TEXT_SCALE: TextStep[] = [
    { utility: "text-xs", token: "--text-xs", value: "0.75rem", px: "12px" },
    { utility: "text-sm", token: "--text-sm", value: "0.875rem", px: "14px" },
    { utility: "text-base", token: "--text-base", value: "1rem", px: "16px" },
    { utility: "text-lg", token: "--text-lg", value: "1.125rem", px: "18px" },
    { utility: "text-xl", token: "--text-xl", value: "1.25rem", px: "20px" },
    { utility: "text-2xl", token: "--text-2xl", value: "1.5rem", px: "24px" },
    { utility: "text-3xl", token: "--text-3xl", value: "1.875rem", px: "30px" },
    { utility: "text-4xl", token: "--text-4xl", value: "2.25rem", px: "36px" },
    { utility: "text-5xl", token: "--text-5xl", value: "3rem", px: "48px" },
    { utility: "text-6xl", token: "--text-6xl", value: "3.75rem", px: "60px" },
    { utility: "text-7xl", token: "--text-7xl", value: "4.5rem", px: "72px" },
];

export const LEADING_SCALE: ScaleStep[] = [
    { utility: "leading-tight", token: "--leading-tight", value: "1.25" },
    { utility: "leading-snug", token: "--leading-snug", value: "1.375" },
    { utility: "leading-normal", token: "--leading-normal", value: "1.5" },
    { utility: "leading-relaxed", token: "--leading-relaxed", value: "1.625" },
];

export const WEIGHT_SCALE: ScaleStep[] = [
    { utility: "font-normal", token: "--font-weight-normal", value: "400" },
    { utility: "font-medium", token: "--font-weight-medium", value: "500" },
    { utility: "font-semibold", token: "--font-weight-semibold", value: "600" },
    { utility: "font-bold", token: "--font-weight-bold", value: "700" },
    { utility: "font-extrabold", token: "--font-weight-extrabold", value: "800" },
];

export const FONT_STACKS: FontStack[] = [
    { token: "--font-sans", value: "ui-sans-serif, system-ui, sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\"" },
    { token: "--font-mono", value: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace" },
    { token: "--font-mincho", value: "\"Shippori Mincho\", \"Yu Mincho\", YuMincho, serif" },
];

export const DENSITY_TOKENS: DensityToken[] = [
    { token: "--control-h", value: "2.25rem" },
    { token: "--text-ui", value: "var(--text-sm)" },
    { token: "--text-prose", value: "var(--text-base)" },
];
