"use client";

/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import * as React from "react";
import {
    EditableDataTable,
    type EditableColumn,
    Input,
    NumberInput,
    formatCurrency,
} from "@gunjo/ui";
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { ComponentDemoStates } from "@/components/doc/ComponentDemoStates";
import { useLocale } from "@/components/providers/LocaleProvider";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { EditableDataTableDemo } from "@/components/demos/EditableDataTableDemo";
import { UIXHERO_BASE_URL } from "@/lib/uixhero-links";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import * as React from "react";
import {
  EditableDataTable,
  type EditableColumn,
  Input,
  NumberInput,
  formatCurrency,
} from "@gunjo/ui";

type LineItem = { id: string; name: string; qty: number; price: number };

const initialRows: LineItem[] = [
  { id: "1", name: "デザイン制作", qty: 10, price: 12000 },
  { id: "2", name: "ホスティング", qty: 1, price: 5000 },
];

export function InvoiceLineItems() {
  const [rows, setRows] = React.useState<LineItem[]>(initialRows);
  const idRef = React.useRef(initialRows.length);

  const update = (index: number, patch: Partial<LineItem>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const columns: EditableColumn<LineItem>[] = [
    {
      id: "name",
      header: "品目",
      minWidth: "12rem",
      cell: (row, ctx) => {
        const { ariaLabel, rowIndex } = ctx;
        const { name } = row;
        return (
          <Input
            value={name}
            aria-label={ariaLabel}
            onChange={(e) => update(rowIndex, { name: e.target.value })}
          />
        );
      },
    },
    {
      id: "qty",
      header: "数量",
      align: "right",
      width: "6.5rem",
      cell: (row, ctx) => {
        const { ariaLabel, rowIndex } = ctx;
        const { qty } = row;
        return (
          <NumberInput
            value={qty}
            min={0}
            aria-label={ariaLabel}
            onValueChange={(v) => update(rowIndex, { qty: v })}
          />
        );
      },
    },
    {
      id: "price",
      header: "単価",
      align: "right",
      width: "8rem",
      cell: (row, ctx) => {
        const { ariaLabel, rowIndex } = ctx;
        const { price } = row;
        return (
          <NumberInput
            value={price}
            min={0}
            step={100}
            aria-label={ariaLabel}
            onValueChange={(v) => update(rowIndex, { price: v })}
          />
        );
      },
    },
    {
      id: "amount",
      header: "金額",
      align: "right",
      width: "8rem",
      cell: (row) => (
        <span className="tabular-nums">{formatCurrency(row.qty * row.price)}</span>
      ),
    },
  ];

  const total = rows.reduce((sum, r) => sum + r.qty * r.price, 0);

  return (
    <EditableDataTable
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      minRows={1}
      onAddRow={() => {
        idRef.current += 1;
        setRows((rs) => [
          ...rs,
          { id: String(idRef.current), name: "", qty: 1, price: 0 },
        ]);
      }}
      onRemoveRow={(index) => setRows((rs) => rs.filter((_, i) => i !== index))}
      getRowError={(row) =>
        row.name.trim() === "" ? "品目を入力してください" : undefined
      }
      labels={{
        addRow: "明細を追加",
        removeRow: (i) => i + 1 + "行目を削除",
      }}
      rowLabel={(i) => i + 1 + "行目"}
      renderFooterCell={(column) =>
        column.id === "name" ? (
          <span>合計</span>
        ) : column.id === "amount" ? (
          <span className="tabular-nums">{formatCurrency(total)}</span>
        ) : null
      }
    />
  );
}`;

const propsData = [
    { name: "columns", type: "EditableColumn<TRow>[]", description: "Column defs. Each renders its cell editor via cell(row, ctx); ctx.ariaLabel is a ready-made label." },
    { name: "rows", type: "TRow[]", description: "The (controlled) row data — the consumer owns it." },
    { name: "getRowId", type: "(row, index) => string", description: "Stable row key." },
    { name: "onAddRow", type: "() => void", description: "Shows an add-row button when set." },
    { name: "onRemoveRow", type: "(index) => void", description: "Shows a per-row remove button (hidden at/below minRows)." },
    { name: "minRows", type: "number", default: "0", description: "Minimum rows kept." },
    { name: "getRowError", type: "(row, index) => string | undefined", description: "Marks a row invalid; the message is exposed to screen readers." },
    { name: "footer", type: "ReactNode", description: "Totals / balance row, rendered under the body on desktop + mobile." },
    { name: "renderRowCard", type: "(row, ctx) => ReactNode", description: "Custom mobile card body (defaults to stacking each column). Function prop — pass only from a Client Component; from a Server Component it breaks next build. Render props return JSX (no serializable alternative) — wrap in a \"use client\" component to pass from an RSC. (#338)" },
    { name: "variant", type: "\"default\" | \"compact\"", default: "\"default\"", description: "Density." },
    { name: "labels / rowLabel / caption / className", type: "—", description: "Add/remove/empty labels, per-row label, caption, extra classes." },
];

type Locale = "en" | "ja";

type JournalRow = { id: string; account: string; debit: number };

function CompactGridPreview({ locale }: { locale: Locale }) {
    const [rows, setRows] = React.useState<JournalRow[]>(
        locale === "ja"
            ? [
                { id: "1", account: "旅費交通費", debit: 12800 },
                { id: "2", account: "消耗品費", debit: 3400 },
                { id: "3", account: "通信費", debit: 8600 },
            ]
            : [
                { id: "1", account: "Travel", debit: 12800 },
                { id: "2", account: "Supplies", debit: 3400 },
                { id: "3", account: "Telecoms", debit: 8600 },
            ]
    );

    const update = (index: number, patch: Partial<JournalRow>) =>
        setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

    const columns: EditableColumn<JournalRow>[] = [
        {
            id: "account",
            header: locale === "ja" ? "勘定科目" : "Account",
            minWidth: "10rem",
            cell: (row, ctx) => (
                <Input
                    value={row.account}
                    aria-label={ctx.ariaLabel}
                    onChange={(e) => update(ctx.rowIndex, { account: e.target.value })}
                />
            ),
        },
        {
            id: "debit",
            header: locale === "ja" ? "借方" : "Debit",
            align: "right",
            width: "9rem",
            cell: (row, ctx) => (
                <NumberInput
                    value={row.debit}
                    min={0}
                    step={100}
                    aria-label={ctx.ariaLabel}
                    onValueChange={(v) => update(ctx.rowIndex, { debit: v })}
                />
            ),
        },
        {
            id: "formatted",
            header: locale === "ja" ? "表示" : "Formatted",
            align: "right",
            width: "8rem",
            cell: (row) => (
                <span className="tabular-nums">{formatCurrency(row.debit)}</span>
            ),
        },
    ];

    return (
        <div className="w-full">
            <EditableDataTable
                variant="compact"
                columns={columns}
                rows={rows}
                getRowId={(r) => r.id}
                rowLabel={(i) => (locale === "ja" ? `${i + 1}行目` : `Row ${i + 1}`)}
            />
        </div>
    );
}

type Entry = { id: string; account: string; debit: number; credit: number };

function BalanceGridPreview({ locale }: { locale: Locale }) {
    const [rows, setRows] = React.useState<Entry[]>(
        locale === "ja"
            ? [
                { id: "1", account: "現金", debit: 50000, credit: 0 },
                { id: "2", account: "売上高", debit: 0, credit: 48000 },
            ]
            : [
                { id: "1", account: "Cash", debit: 50000, credit: 0 },
                { id: "2", account: "Revenue", debit: 0, credit: 48000 },
            ]
    );

    const update = (index: number, patch: Partial<Entry>) =>
        setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

    const debit = rows.reduce((sum, r) => sum + r.debit, 0);
    const credit = rows.reduce((sum, r) => sum + r.credit, 0);
    const balanced = debit === credit;

    const columns: EditableColumn<Entry>[] = [
        {
            id: "account",
            header: locale === "ja" ? "勘定科目" : "Account",
            minWidth: "10rem",
            cell: (row, ctx) => (
                <Input
                    value={row.account}
                    aria-label={ctx.ariaLabel}
                    onChange={(e) => update(ctx.rowIndex, { account: e.target.value })}
                />
            ),
        },
        {
            id: "debit",
            header: locale === "ja" ? "借方" : "Debit",
            align: "right",
            width: "9rem",
            cell: (row, ctx) => (
                <NumberInput
                    value={row.debit}
                    min={0}
                    step={1000}
                    aria-label={ctx.ariaLabel}
                    onValueChange={(v) => update(ctx.rowIndex, { debit: v })}
                />
            ),
        },
        {
            id: "credit",
            header: locale === "ja" ? "貸方" : "Credit",
            align: "right",
            width: "9rem",
            cell: (row, ctx) => (
                <NumberInput
                    value={row.credit}
                    min={0}
                    step={1000}
                    aria-label={ctx.ariaLabel}
                    onValueChange={(v) => update(ctx.rowIndex, { credit: v })}
                />
            ),
        },
    ];

    const outOfBalance = locale === "ja"
        ? `差額 ${formatCurrency(debit - credit)} が残っています`
        : `Out of balance by ${formatCurrency(debit - credit)}`;

    return (
        <div className="w-full">
            <EditableDataTable
                columns={columns}
                rows={rows}
                getRowId={(r) => r.id}
                rowLabel={(i) => (locale === "ja" ? `${i + 1}行目` : `Row ${i + 1}`)}
                renderFooterCell={(column) =>
                    column.id === "debit" ? (
                        <span className="tabular-nums">{formatCurrency(debit)}</span>
                    ) : column.id === "credit" ? (
                        <span className="tabular-nums">{formatCurrency(credit)}</span>
                    ) : null
                }
                footer={
                    <span className={balanced ? "text-success-strong" : "text-destructive"}>
                        {balanced
                            ? (locale === "ja" ? "貸借は一致しています" : "Debits and credits balance")
                            : outOfBalance}
                    </span>
                }
            />
        </div>
    );
}

type Guest = { id: string; name: string; company: string };

function EmptyGridPreview({ locale }: { locale: Locale }) {
    const [rows, setRows] = React.useState<Guest[]>([]);
    const nextId = React.useRef(0);

    const update = (index: number, patch: Partial<Guest>) =>
        setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

    const columns: EditableColumn<Guest>[] = [
        {
            id: "name",
            header: locale === "ja" ? "氏名" : "Name",
            minWidth: "10rem",
            cell: (row, ctx) => (
                <Input
                    value={row.name}
                    aria-label={ctx.ariaLabel}
                    onChange={(e) => update(ctx.rowIndex, { name: e.target.value })}
                />
            ),
        },
        {
            id: "company",
            header: locale === "ja" ? "所属" : "Company",
            minWidth: "10rem",
            cell: (row, ctx) => (
                <Input
                    value={row.company}
                    aria-label={ctx.ariaLabel}
                    onChange={(e) => update(ctx.rowIndex, { company: e.target.value })}
                />
            ),
        },
    ];

    return (
        <div className="w-full">
            <EditableDataTable
                columns={columns}
                rows={rows}
                getRowId={(r) => r.id}
                caption={locale === "ja"
                    ? "来場者の名簿。行を足して1人ずつ入力します。"
                    : "Guest list. Add a row for each person."}
                labels={locale === "ja"
                    ? {
                        addRow: "来場者を追加",
                        removeRow: (i) => `${i + 1}人目を削除`,
                        empty: "まだ誰も登録されていません。",
                    }
                    : {
                        addRow: "Add a guest",
                        removeRow: (i) => `Remove guest ${i + 1}`,
                        empty: "Nobody has been added yet.",
                    }}
                rowLabel={(i) => (locale === "ja" ? `${i + 1}人目` : `Guest ${i + 1}`)}
                onAddRow={() => {
                    nextId.current += 1;
                    setRows((rs) => [
                        ...rs,
                        { id: String(nextId.current), name: "", company: "" },
                    ]);
                }}
                onRemoveRow={(index) => setRows((rs) => rs.filter((_, i) => i !== index))}
            />
        </div>
    );
}

export default function EditableDataTableDocPage() {
    const { locale } = useLocale();
    const title = meta.editableDataTable.title ?? "EditableDataTable";
    const description = meta.editableDataTable.description ?? "";

    return (
        <ComponentLayout
            title={title}
            description={description}
            usedComponents={[
                { name: "Button", href: "/docs/components/button" },
            ]}
            relatedComponents={[
                { name: "DataTable", href: "/docs/components/data-table" },
                { name: "ActionDataTable", href: "/docs/components/action-data-table" },
                { name: "EditableField", href: "/docs/components/editable-field" },
                { name: "AmountBreakdown", href: "/docs/components/amount-breakdown" },
            ]}
            uixheroLinks={[
                {
                    label: locale === "ja" ? "UIXHERO: テーブル（Table）" : "UIXHERO: Table (in Japanese)",
                    href: `${UIXHERO_BASE_URL}/resources/ui-components/table`,
                    relation: "nearest",
                },
            ]}
        >
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <div className="w-full">
                    <EditableDataTableDemo />
                </div>
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0" id="states">
                    {locale === "ja" ? "状態とバリエーション" : "States and variants"}
                </h2>
                <p className="text-sm leading-relaxed text-muted-foreground">
                    {locale === "ja"
                        ? "升目の中身は呼ぶ側が決めるので、この部品で変わるのは骨組みのほうです。行の高さ（variant）、合計の出し方（列ごとの renderFooterCell と、列に紐づかない footer）、そして行が1つも無いときの見え方（labels.empty と caption）の3つが、画面ごとに変える口になります。"
                        : "Because the caller owns what goes in each cell, what varies here is the frame around them: row height (variant), how totals are shown (renderFooterCell per column, or a footer that belongs to no column), and what the grid looks like with no rows at all (labels.empty and caption)."}
                </p>
                <ComponentDemoStates
                    states={[
                        {
                            key: "compact",
                            title: locale === "ja" ? "行を詰める" : "Tighter rows",
                            description: locale === "ja"
                                ? "variant=\"compact\" は升目の余白を詰めます。1画面に何十行も並べる仕訳や棚卸のように、打ち込む回数が多くて縦の移動が負担になる表で使います。入力欄の大きさ自体は変わらないので、押しにくくはなりません。"
                                : "variant=\"compact\" tightens the cell padding. Reach for it on journals and stocktakes where dozens of rows are typed in one sitting and the vertical travel is the cost. The editors themselves keep their size, so nothing becomes harder to hit.",
                            preview: <CompactGridPreview locale={locale} />,
                            code: locale === "ja"
                                ? `import * as React from "react";
import {
  EditableDataTable,
  type EditableColumn,
  Input,
  NumberInput,
  formatCurrency,
} from "@gunjo/ui";

type JournalRow = { id: string; account: string; debit: number };

const initialRows: JournalRow[] = [
  { id: "1", account: "旅費交通費", debit: 12800 },
  { id: "2", account: "消耗品費", debit: 3400 },
  { id: "3", account: "通信費", debit: 8600 },
];

export function CompactJournal() {
  const [rows, setRows] = React.useState<JournalRow[]>(initialRows);

  const update = (index: number, patch: Partial<JournalRow>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const columns: EditableColumn<JournalRow>[] = [
    {
      id: "account",
      header: "勘定科目",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.account}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { account: e.target.value })}
        />
      ),
    },
    {
      id: "debit",
      header: "借方",
      align: "right",
      width: "9rem",
      cell: (row, ctx) => (
        <NumberInput
          value={row.debit}
          min={0}
          step={100}
          aria-label={ctx.ariaLabel}
          onValueChange={(v) => update(ctx.rowIndex, { debit: v })}
        />
      ),
    },
    {
      id: "formatted",
      header: "表示",
      align: "right",
      width: "8rem",
      cell: (row) => (
        <span className="tabular-nums">{formatCurrency(row.debit)}</span>
      ),
    },
  ];

  return (
    <EditableDataTable
      variant="compact"
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      rowLabel={(i) => i + 1 + "行目"}
    />
  );
}`
                                : `import * as React from "react";
import {
  EditableDataTable,
  type EditableColumn,
  Input,
  NumberInput,
  formatCurrency,
} from "@gunjo/ui";

type JournalRow = { id: string; account: string; debit: number };

const initialRows: JournalRow[] = [
  { id: "1", account: "Travel", debit: 12800 },
  { id: "2", account: "Supplies", debit: 3400 },
  { id: "3", account: "Telecoms", debit: 8600 },
];

export function CompactJournal() {
  const [rows, setRows] = React.useState<JournalRow[]>(initialRows);

  const update = (index: number, patch: Partial<JournalRow>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const columns: EditableColumn<JournalRow>[] = [
    {
      id: "account",
      header: "Account",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.account}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { account: e.target.value })}
        />
      ),
    },
    {
      id: "debit",
      header: "Debit",
      align: "right",
      width: "9rem",
      cell: (row, ctx) => (
        <NumberInput
          value={row.debit}
          min={0}
          step={100}
          aria-label={ctx.ariaLabel}
          onValueChange={(v) => update(ctx.rowIndex, { debit: v })}
        />
      ),
    },
    {
      id: "formatted",
      header: "Formatted",
      align: "right",
      width: "8rem",
      cell: (row) => (
        <span className="tabular-nums">{formatCurrency(row.debit)}</span>
      ),
    },
  ];

  return (
    <EditableDataTable
      variant="compact"
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      rowLabel={(i) => "Row " + (i + 1)}
    />
  );
}`,
                        },
                        {
                            key: "footer",
                            title: locale === "ja" ? "列に紐づかない帯" : "A footer that belongs to no column",
                            description: locale === "ja"
                                ? "renderFooterCell は列の下に数字を置きますが、貸借が合っているかのような判定は列の下には収まりません。footer は表の幅いっぱいに1本の帯を出す口で、デスクトップでもスマホでも同じ位置に付きます。両方を同時に使えます。"
                                : "renderFooterCell puts a number under a column, but a verdict such as whether the two sides balance does not belong under any one of them. footer renders a single full-width band instead, in the same place on desktop and on a phone. The two can be used together.",
                            preview: <BalanceGridPreview locale={locale} />,
                            code: locale === "ja"
                                ? `import * as React from "react";
import {
  EditableDataTable,
  type EditableColumn,
  Input,
  NumberInput,
  formatCurrency,
} from "@gunjo/ui";

type Entry = { id: string; account: string; debit: number; credit: number };

const initialRows: Entry[] = [
  { id: "1", account: "現金", debit: 50000, credit: 0 },
  { id: "2", account: "売上高", debit: 0, credit: 48000 },
];

export function BalancedJournal() {
  const [rows, setRows] = React.useState<Entry[]>(initialRows);

  const update = (index: number, patch: Partial<Entry>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const debit = rows.reduce((sum, r) => sum + r.debit, 0);
  const credit = rows.reduce((sum, r) => sum + r.credit, 0);
  const balanced = debit === credit;

  const columns: EditableColumn<Entry>[] = [
    {
      id: "account",
      header: "勘定科目",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.account}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { account: e.target.value })}
        />
      ),
    },
    {
      id: "debit",
      header: "借方",
      align: "right",
      width: "9rem",
      cell: (row, ctx) => (
        <NumberInput
          value={row.debit}
          min={0}
          step={1000}
          aria-label={ctx.ariaLabel}
          onValueChange={(v) => update(ctx.rowIndex, { debit: v })}
        />
      ),
    },
    {
      id: "credit",
      header: "貸方",
      align: "right",
      width: "9rem",
      cell: (row, ctx) => (
        <NumberInput
          value={row.credit}
          min={0}
          step={1000}
          aria-label={ctx.ariaLabel}
          onValueChange={(v) => update(ctx.rowIndex, { credit: v })}
        />
      ),
    },
  ];

  return (
    <EditableDataTable
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      rowLabel={(i) => i + 1 + "行目"}
      renderFooterCell={(column) =>
        column.id === "debit" ? (
          <span className="tabular-nums">{formatCurrency(debit)}</span>
        ) : column.id === "credit" ? (
          <span className="tabular-nums">{formatCurrency(credit)}</span>
        ) : null
      }
      footer={
        <span className={balanced ? "text-success-strong" : "text-destructive"}>
          {balanced
            ? "貸借は一致しています"
            : "差額 " + formatCurrency(debit - credit) + " が残っています"}
        </span>
      }
    />
  );
}`
                                : `import * as React from "react";
import {
  EditableDataTable,
  type EditableColumn,
  Input,
  NumberInput,
  formatCurrency,
} from "@gunjo/ui";

type Entry = { id: string; account: string; debit: number; credit: number };

const initialRows: Entry[] = [
  { id: "1", account: "Cash", debit: 50000, credit: 0 },
  { id: "2", account: "Revenue", debit: 0, credit: 48000 },
];

export function BalancedJournal() {
  const [rows, setRows] = React.useState<Entry[]>(initialRows);

  const update = (index: number, patch: Partial<Entry>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const debit = rows.reduce((sum, r) => sum + r.debit, 0);
  const credit = rows.reduce((sum, r) => sum + r.credit, 0);
  const balanced = debit === credit;

  const columns: EditableColumn<Entry>[] = [
    {
      id: "account",
      header: "Account",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.account}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { account: e.target.value })}
        />
      ),
    },
    {
      id: "debit",
      header: "Debit",
      align: "right",
      width: "9rem",
      cell: (row, ctx) => (
        <NumberInput
          value={row.debit}
          min={0}
          step={1000}
          aria-label={ctx.ariaLabel}
          onValueChange={(v) => update(ctx.rowIndex, { debit: v })}
        />
      ),
    },
    {
      id: "credit",
      header: "Credit",
      align: "right",
      width: "9rem",
      cell: (row, ctx) => (
        <NumberInput
          value={row.credit}
          min={0}
          step={1000}
          aria-label={ctx.ariaLabel}
          onValueChange={(v) => update(ctx.rowIndex, { credit: v })}
        />
      ),
    },
  ];

  return (
    <EditableDataTable
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      rowLabel={(i) => "Row " + (i + 1)}
      renderFooterCell={(column) =>
        column.id === "debit" ? (
          <span className="tabular-nums">{formatCurrency(debit)}</span>
        ) : column.id === "credit" ? (
          <span className="tabular-nums">{formatCurrency(credit)}</span>
        ) : null
      }
      footer={
        <span className={balanced ? "text-success-strong" : "text-destructive"}>
          {balanced
            ? "Debits and credits balance"
            : "Out of balance by " + formatCurrency(debit - credit)}
        </span>
      }
    />
  );
}`,
                        },
                        {
                            key: "empty",
                            title: locale === "ja" ? "行が1つも無いとき" : "With no rows at all",
                            description: locale === "ja"
                                ? "rows が空でも表は消えず、見出しと空の知らせが残ります。既定の知らせは英語の \"No rows.\" なので、日本語の画面では labels.empty で書き換えます。caption は表そのものの説明で、読み上げにも入ります。行を足す口（onAddRow）は空のときこそ要ります。"
                                : "An empty rows array does not remove the grid: the headers stay, with a line saying there is nothing yet. labels.empty replaces the built-in \"No rows.\" when the surrounding copy calls for different words, and caption describes the grid itself, including to screen readers. The add-row affordance matters most in exactly this state.",
                            preview: <EmptyGridPreview locale={locale} />,
                            code: locale === "ja"
                                ? `import * as React from "react";
import { EditableDataTable, type EditableColumn, Input } from "@gunjo/ui";

type Guest = { id: string; name: string; company: string };

export function GuestList() {
  const [rows, setRows] = React.useState<Guest[]>([]);
  const nextId = React.useRef(0);

  const update = (index: number, patch: Partial<Guest>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const columns: EditableColumn<Guest>[] = [
    {
      id: "name",
      header: "氏名",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.name}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { name: e.target.value })}
        />
      ),
    },
    {
      id: "company",
      header: "所属",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.company}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { company: e.target.value })}
        />
      ),
    },
  ];

  return (
    <EditableDataTable
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      caption="来場者の名簿。行を足して1人ずつ入力します。"
      labels={{
        addRow: "来場者を追加",
        removeRow: (i) => i + 1 + "人目を削除",
        empty: "まだ誰も登録されていません。",
      }}
      rowLabel={(i) => i + 1 + "人目"}
      onAddRow={() => {
        nextId.current += 1;
        setRows((rs) => [
          ...rs,
          { id: String(nextId.current), name: "", company: "" },
        ]);
      }}
      onRemoveRow={(index) => setRows((rs) => rs.filter((_, i) => i !== index))}
    />
  );
}`
                                : `import * as React from "react";
import { EditableDataTable, type EditableColumn, Input } from "@gunjo/ui";

type Guest = { id: string; name: string; company: string };

export function GuestList() {
  const [rows, setRows] = React.useState<Guest[]>([]);
  const nextId = React.useRef(0);

  const update = (index: number, patch: Partial<Guest>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const columns: EditableColumn<Guest>[] = [
    {
      id: "name",
      header: "Name",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.name}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { name: e.target.value })}
        />
      ),
    },
    {
      id: "company",
      header: "Company",
      minWidth: "10rem",
      cell: (row, ctx) => (
        <Input
          value={row.company}
          aria-label={ctx.ariaLabel}
          onChange={(e) => update(ctx.rowIndex, { company: e.target.value })}
        />
      ),
    },
  ];

  return (
    <EditableDataTable
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      caption="Guest list. Add a row for each person."
      labels={{
        addRow: "Add a guest",
        removeRow: (i) => "Remove guest " + (i + 1),
        empty: "Nobody has been added yet.",
      }}
      rowLabel={(i) => "Guest " + (i + 1)}
      onAddRow={() => {
        nextId.current += 1;
        setRows((rs) => [
          ...rs,
          { id: String(nextId.current), name: "", company: "" },
        ]);
      }}
      onRemoveRow={(index) => setRows((rs) => rs.filter((_, i) => i !== index))}
    />
  );
}`,
                        },
                    ]}
                />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
            <section className="space-y-4">
                <div className="border-b pb-2">
                    <h2 className="scroll-m-20 text-2xl font-semibold tracking-tight" id="design-decisions">
                        {locale === "ja" ? "設計の判断" : "Design decisions"}
                    </h2>
                </div>
                {locale === "ja" ? (
                    <ul className="ml-4 list-disc space-y-2 text-sm text-muted-foreground">
                        <li>
                            <strong>升目の中身は部品が持たない。</strong><code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">columns[].cell</code> が返した要素をそのまま置くので、入力欄でも選択でも、計算した読み取り専用の文字でもかまいません。部品が持つのは骨組み（列幅・揃え・行の追加と削除・合計行）だけです。
                        </li>
                        <li>
                            <strong>読み上げ用の名前を作って渡す。</strong><code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">cell</code> の第2引数には「2行目 単価」のような文字列（<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">ariaLabel</code>）が入っています。呼ぶ側はこれを入力欄の <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">aria-label</code> に載せるだけで済みます。名前の無い入力欄が並んだ表を作らせないための形です。
                        </li>
                        <li>
                            <strong>スマホでは表をやめてカードに積み直す。</strong>デスクトップは <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">table</code>、<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">md</code> 未満は1行が1枚のカードになり、<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">renderFooterCell</code> の合計もそれぞれの形で出ます（#210）。入力欄が並ぶ表は横に流すと打ち込めなくなるので、資料の「スクロール耐性」をここでは「形を変える」で解きました。
                            <br />
                            一般の表の設計は UIXHERO の「テーブル」にあります。
                        </li>
                    </ul>
                ) : (
                    <ul className="ml-4 list-disc space-y-2 text-sm text-muted-foreground">
                        <li>
                            <strong>The component owns no cell content.</strong> Whatever <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">columns[].cell</code> returns is placed as-is: an input, a select, or read-only derived text. All the component supplies is the frame: column widths, alignment, add and remove row, the footer row.
                        </li>
                        <li>
                            <strong>It hands you the accessible name.</strong> The second argument to <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">cell</code> carries <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">ariaLabel</code>, a ready-made string like &ldquo;row 2, unit price&rdquo;; the caller just spreads it onto the editor&rsquo;s <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">aria-label</code>. That is how a grid of unlabelled inputs is prevented by construction.
                        </li>
                        <li>
                            <strong>Below <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">md</code> the table becomes cards.</strong> Desktop renders a real <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">table</code>; on narrow screens each row becomes a card, and <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">renderFooterCell</code> totals render in both shapes (#210). A grid of inputs is unusable when it scrolls sideways, so the article&rsquo;s scroll-resilience principle is answered here by changing shape instead.
                            <br />
                            The general design of tables is covered by UIXHERO&rsquo;s table article.
                        </li>
                    </ul>
                )}
            </section>
        </ComponentLayout>
    );
}
