"use client";

/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { useLocale } from "@/components/providers/LocaleProvider";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { EditableDataTableDemo } from "@/components/demos/EditableDataTableDemo";
import { UIXHERO_BASE_URL } from "@/lib/uixhero-links";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import * as React from "react";
import {
  EditableDataTable,
  type EditableColumn,
  Input,
  NumberInput,
  formatCurrency,
} from "@gunjo/ui";

type LineItem = { id: string; name: string; qty: number; price: number };

const initialRows: LineItem[] = [
  { id: "1", name: "デザイン制作", qty: 10, price: 12000 },
  { id: "2", name: "ホスティング", qty: 1, price: 5000 },
];

export function InvoiceLineItems() {
  const [rows, setRows] = React.useState<LineItem[]>(initialRows);
  const idRef = React.useRef(initialRows.length);

  const update = (index: number, patch: Partial<LineItem>) =>
    setRows((rs) => rs.map((r, i) => (i === index ? { ...r, ...patch } : r)));

  const columns: EditableColumn<LineItem>[] = [
    {
      id: "name",
      header: "品目",
      minWidth: "12rem",
      cell: (row, ctx) => {
        const { ariaLabel, rowIndex } = ctx;
        const { name } = row;
        return (
          <Input
            value={name}
            aria-label={ariaLabel}
            onChange={(e) => update(rowIndex, { name: e.target.value })}
          />
        );
      },
    },
    {
      id: "qty",
      header: "数量",
      align: "right",
      width: "6.5rem",
      cell: (row, ctx) => {
        const { ariaLabel, rowIndex } = ctx;
        const { qty } = row;
        return (
          <NumberInput
            value={qty}
            min={0}
            aria-label={ariaLabel}
            onValueChange={(v) => update(rowIndex, { qty: v })}
          />
        );
      },
    },
    {
      id: "price",
      header: "単価",
      align: "right",
      width: "8rem",
      cell: (row, ctx) => {
        const { ariaLabel, rowIndex } = ctx;
        const { price } = row;
        return (
          <NumberInput
            value={price}
            min={0}
            step={100}
            aria-label={ariaLabel}
            onValueChange={(v) => update(rowIndex, { price: v })}
          />
        );
      },
    },
    {
      id: "amount",
      header: "金額",
      align: "right",
      width: "8rem",
      cell: (row) => (
        <span className="tabular-nums">{formatCurrency(row.qty * row.price)}</span>
      ),
    },
  ];

  const total = rows.reduce((sum, r) => sum + r.qty * r.price, 0);

  return (
    <EditableDataTable
      columns={columns}
      rows={rows}
      getRowId={(r) => r.id}
      minRows={1}
      onAddRow={() => {
        idRef.current += 1;
        setRows((rs) => [
          ...rs,
          { id: String(idRef.current), name: "", qty: 1, price: 0 },
        ]);
      }}
      onRemoveRow={(index) => setRows((rs) => rs.filter((_, i) => i !== index))}
      getRowError={(row) =>
        row.name.trim() === "" ? "品目を入力してください" : undefined
      }
      labels={{
        addRow: "明細を追加",
        removeRow: (i) => i + 1 + "行目を削除",
      }}
      rowLabel={(i) => i + 1 + "行目"}
      renderFooterCell={(column) =>
        column.id === "name" ? (
          <span>合計</span>
        ) : column.id === "amount" ? (
          <span className="tabular-nums">{formatCurrency(total)}</span>
        ) : null
      }
    />
  );
}`;

const propsData = [
    { name: "columns", type: "EditableColumn<TRow>[]", description: "Column defs. Each renders its cell editor via cell(row, ctx); ctx.ariaLabel is a ready-made label." },
    { name: "rows", type: "TRow[]", description: "The (controlled) row data — the consumer owns it." },
    { name: "getRowId", type: "(row, index) => string", description: "Stable row key." },
    { name: "onAddRow", type: "() => void", description: "Shows an add-row button when set." },
    { name: "onRemoveRow", type: "(index) => void", description: "Shows a per-row remove button (hidden at/below minRows)." },
    { name: "minRows", type: "number", default: "0", description: "Minimum rows kept." },
    { name: "getRowError", type: "(row, index) => string | undefined", description: "Marks a row invalid; the message is exposed to screen readers." },
    { name: "footer", type: "ReactNode", description: "Totals / balance row, rendered under the body on desktop + mobile." },
    { name: "renderRowCard", type: "(row, ctx) => ReactNode", description: "Custom mobile card body (defaults to stacking each column). Function prop — pass only from a Client Component; from a Server Component it breaks next build. Render props return JSX (no serializable alternative) — wrap in a \"use client\" component to pass from an RSC. (#338)" },
    { name: "variant", type: "\"default\" | \"compact\"", default: "\"default\"", description: "Density." },
    { name: "labels / rowLabel / caption / className", type: "—", description: "Add/remove/empty labels, per-row label, caption, extra classes." },
];

export default function EditableDataTableDocPage() {
    const { locale } = useLocale();
    const title = meta.editableDataTable.title ?? "EditableDataTable";
    const description = meta.editableDataTable.description ?? "";

    return (
        <ComponentLayout
            title={title}
            description={description}
            usedComponents={[
                { name: "Button", href: "/docs/components/button" },
            ]}
            relatedComponents={[
                { name: "DataTable", href: "/docs/components/data-table" },
                { name: "ActionDataTable", href: "/docs/components/action-data-table" },
                { name: "EditableField", href: "/docs/components/editable-field" },
                { name: "AmountBreakdown", href: "/docs/components/amount-breakdown" },
            ]}
            uixheroLinks={[
                {
                    label: locale === "ja" ? "UIXHERO: テーブル（Table）" : "UIXHERO: Table (in Japanese)",
                    href: `${UIXHERO_BASE_URL}/resources/ui-components/table`,
                    relation: "nearest",
                },
            ]}
        >
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <div className="w-full">
                    <EditableDataTableDemo />
                </div>
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
            <section className="space-y-4">
                <div className="border-b pb-2">
                    <h2 className="scroll-m-20 text-2xl font-semibold tracking-tight" id="design-decisions">
                        {locale === "ja" ? "設計の判断" : "Design decisions"}
                    </h2>
                </div>
                {locale === "ja" ? (
                    <ul className="ml-4 list-disc space-y-2 text-sm text-muted-foreground">
                        <li>
                            <strong>升目の中身は部品が持たない。</strong><code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">columns[].cell</code> が返した要素をそのまま置くので、入力欄でも選択でも、計算した読み取り専用の文字でもかまいません。部品が持つのは骨組み（列幅・揃え・行の追加と削除・合計行）だけです。
                        </li>
                        <li>
                            <strong>読み上げ用の名前を作って渡す。</strong><code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">cell</code> の第2引数には「2行目 単価」のような文字列（<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">ariaLabel</code>）が入っています。呼ぶ側はこれを入力欄の <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">aria-label</code> に載せるだけで済みます。名前の無い入力欄が並んだ表を作らせないための形です。
                        </li>
                        <li>
                            <strong>スマホでは表をやめてカードに積み直す。</strong>デスクトップは <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">table</code>、<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">md</code> 未満は1行が1枚のカードになり、<code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">renderFooterCell</code> の合計もそれぞれの形で出ます（#210）。入力欄が並ぶ表は横に流すと打ち込めなくなるので、資料の「スクロール耐性」をここでは「形を変える」で解きました。
                            <br />
                            一般の表の設計は UIXHERO の「テーブル」にあります。
                        </li>
                    </ul>
                ) : (
                    <ul className="ml-4 list-disc space-y-2 text-sm text-muted-foreground">
                        <li>
                            <strong>The component owns no cell content.</strong> Whatever <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">columns[].cell</code> returns is placed as-is: an input, a select, or read-only derived text. All the component supplies is the frame: column widths, alignment, add and remove row, the footer row.
                        </li>
                        <li>
                            <strong>It hands you the accessible name.</strong> The second argument to <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">cell</code> carries <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">ariaLabel</code>, a ready-made string like &ldquo;row 2, unit price&rdquo;; the caller just spreads it onto the editor&rsquo;s <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">aria-label</code>. That is how a grid of unlabelled inputs is prevented by construction.
                        </li>
                        <li>
                            <strong>Below <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">md</code> the table becomes cards.</strong> Desktop renders a real <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">table</code>; on narrow screens each row becomes a card, and <code className="rounded bg-muted px-1 py-0.5 font-mono text-xs">renderFooterCell</code> totals render in both shapes (#210). A grid of inputs is unusable when it scrolls sideways, so the article&rsquo;s scroll-resilience principle is answered here by changing shape instead.
                            <br />
                            The general design of tables is covered by UIXHERO&rsquo;s table article.
                        </li>
                    </ul>
                )}
            </section>
        </ComponentLayout>
    );
}
