/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { EditableDataTableDemo } from "@/components/demos/EditableDataTableDemo";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

const usageCode = `import { EditableDataTable, type EditableColumn, Input, NumberInput, formatCurrency } from "@gunjo/ui"

type LineItem = { id: string; name: string; qty: number; price: number }

export function Example() {
  const [rows, setRows] = React.useState<LineItem[]>([/* ... */])
  const update = (i: number, patch: Partial<LineItem>) =>
    setRows((rs) => rs.map((r, idx) => (idx === i ? { ...r, ...patch } : r)))

  const columns: EditableColumn<LineItem>[] = [
    { id: "name", header: "品目",
      cell: (row, ctx) => <Input value={row.name} aria-label={ctx.ariaLabel}
        onChange={(e) => update(ctx.rowIndex, { name: e.target.value })} /> },
    { id: "qty", header: "数量", align: "right",
      cell: (row, ctx) => <NumberInput value={row.qty} aria-label={ctx.ariaLabel}
        onValueChange={(v) => update(ctx.rowIndex, { qty: v })} /> },
    { id: "amount", header: "金額", align: "right",
      cell: (row) => formatCurrency(row.qty * row.price) },
  ]

  return (
    <EditableDataTable columns={columns} rows={rows} getRowId={(r) => r.id} minRows={1}
      onAddRow={() => setRows((rs) => [...rs, makeRow()])}
      onRemoveRow={(i) => setRows((rs) => rs.filter((_, idx) => idx !== i))}
      footer={<Totals rows={rows} />} />
  )
}`;

const propsData = [
    { name: "columns", type: "EditableColumn<TRow>[]", description: "Column defs. Each renders its cell editor via cell(row, ctx); ctx.ariaLabel is a ready-made label." },
    { name: "rows", type: "TRow[]", description: "The (controlled) row data — the consumer owns it." },
    { name: "getRowId", type: "(row, index) => string", description: "Stable row key." },
    { name: "onAddRow", type: "() => void", description: "Shows an add-row button when set." },
    { name: "onRemoveRow", type: "(index) => void", description: "Shows a per-row remove button (hidden at/below minRows)." },
    { name: "minRows", type: "number", default: "0", description: "Minimum rows kept." },
    { name: "getRowError", type: "(row, index) => string | undefined", description: "Marks a row invalid; the message is exposed to screen readers." },
    { name: "footer", type: "ReactNode", description: "Totals / balance row, rendered under the body on desktop + mobile." },
    { name: "renderRowCard", type: "(row, ctx) => ReactNode", description: "Custom mobile card body (defaults to stacking each column)." },
    { name: "variant", type: "\"default\" | \"compact\"", default: "\"default\"", description: "Density." },
    { name: "labels / rowLabel / caption / className", type: "—", description: "Add/remove/empty labels, per-row label, caption, extra classes." },
];

export default function EditableDataTableDocPage() {
    const title = meta.editableDataTable.title ?? "EditableDataTable";
    const description = meta.editableDataTable.description ?? "";

    return (
        <ComponentLayout title={title} description={description}>
            <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
                <div className="w-full">
                    <EditableDataTableDemo />
                </div>
            </ComponentPreview>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
                <PropsTable data={propsData} />
            </div>

            <div className="space-y-4">
                <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
                <div className="rounded-md border bg-muted font-mono text-sm max-h-[420px] overflow-auto">
                    <CodeBlock code={usageCode} />
                </div>
            </div>
        </ComponentLayout>
    );
}
