/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import displayMetadata from "@design/display-metadata.json";

import { Gallery } from "@gunjo/ui";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

// Inline SVG data URIs keep the demo offline and deterministic.
const swatch = (bg: string, label: string) =>
  `data:image/svg+xml,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="400" height="400" fill="${bg}"/><text x="50%" y="50%" fill="#fff" font-family="sans-serif" font-size="40" text-anchor="middle" dominant-baseline="middle">${label}</text></svg>`
  )}`;

const galleryImages = [
  { src: swatch("#0f172a", "1"), alt: "Front view" },
  { src: swatch("#1e3a8a", "2"), alt: "Side view" },
  { src: swatch("#4d7c0f", "3"), alt: "Back view" },
  { src: swatch("#b45309", "4"), alt: "Detail view" },
];

const usageCode = `import { Gallery } from "@gunjo/ui"

const images = [
  { src: "/front.jpg", alt: "Front view" },
  { src: "/side.jpg", alt: "Side view" },
]

export function Example() {
  return <Gallery images={images} aspectRatio="square" />
}`;

const propsData = [
  { name: "images", type: "{ src: string; alt: string }[]", description: "Images shown in the main view + thumbnail strip." },
  { name: "value", type: "number", description: "Controlled active index (omit for internal state)." },
  { name: "onValueChange", type: "(index: number) => void", description: "Active-index change handler." },
  { name: "defaultIndex", type: "number", default: "0", description: "Initial active index when uncontrolled." },
  { name: "thumbnailPosition", type: "\"bottom\" | \"start\"", default: "\"bottom\"", description: "Thumbnail strip position." },
  { name: "aspectRatio", type: "\"square\" | \"video\" | \"auto\" | \"portrait\" | \"wide\"", default: "\"square\"", description: "Main image aspect ratio." },
  { name: "className", type: "string", description: "Additional CSS class names." },
];

export default function GalleryDocPage() {
  const title = meta.gallery.title ?? "Gallery";
  const description = meta.gallery.description ?? "";

  return (
    <ComponentLayout title={title} description={description}>
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <div className="w-full max-w-sm">
          <Gallery images={galleryImages} aspectRatio="square" />
        </div>
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
