"use client";

/**
 * Generated by `npm run design:sync:docs-pages`, then hand-edited with a real demo.
 */
import * as React from "react";
import { ComponentLayout, ComponentPreview } from "@/components/doc/ComponentHelpers";
import { ComponentDemoStates } from "@/components/doc/ComponentDemoStates";
import { PropsTable } from "@/components/doc/PropsTable";
import { CodeBlock } from "@/components/doc/CodeBlock";
import { useLocale } from "@/components/providers/LocaleProvider";
import displayMetadata from "@design/display-metadata.json";

import { Gallery } from "@gunjo/ui";

const meta = displayMetadata as Record<string, { title?: string; description?: string }>;

// Inline SVG data URIs keep the demo offline and deterministic.
const swatch = (bg: string, label: string) =>
  `data:image/svg+xml,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400"><rect width="400" height="400" fill="${bg}"/><text x="50%" y="50%" fill="#fff" font-family="sans-serif" font-size="40" text-anchor="middle" dominant-baseline="middle">${label}</text></svg>`
  )}`;

const galleryImages = [
  { src: swatch("#0f172a", "1"), alt: "Front view" },
  { src: swatch("#1e3a8a", "2"), alt: "Side view" },
  { src: swatch("#4d7c0f", "3"), alt: "Back view" },
  { src: swatch("#b45309", "4"), alt: "Detail view" },
];

const usageCode = `import { Gallery } from "@gunjo/ui"

const images = [
  { src: "/front.jpg", alt: "Front view" },
  { src: "/side.jpg", alt: "Side view" },
]

export function Example() {
  return <Gallery images={images} aspectRatio="square" />
}`;

const propsData = [
  { name: "images", type: "{ src: string; alt: string }[]", description: "Images shown in the main view + thumbnail strip." },
  { name: "value", type: "number", description: "Controlled active index (omit for internal state)." },
  { name: "onValueChange", type: "(index: number) => void", description: "Active-index change handler." },
  { name: "defaultIndex", type: "number", default: "0", description: "Initial active index when uncontrolled." },
  { name: "thumbnailPosition", type: "\"bottom\" | \"start\"", default: "\"bottom\"", description: "Thumbnail strip position." },
  { name: "aspectRatio", type: "\"square\" | \"video\" | \"auto\" | \"portrait\" | \"wide\"", default: "\"square\"", description: "Main image aspect ratio." },
  { name: "className", type: "string", description: "Additional CSS class names." },
];

function ControlledGalleryPreview({ locale }: { locale: "en" | "ja" }) {
  const [index, setIndex] = React.useState(0);

  return (
    <div className="flex w-full max-w-sm flex-col gap-2">
      <Gallery images={galleryImages} value={index} onValueChange={setIndex} />
      <p className="text-sm text-muted-foreground">
        {locale === "ja"
          ? `${index + 1} / ${galleryImages.length} 枚目：${galleryImages[index].alt}`
          : `Image ${index + 1} of ${galleryImages.length}: ${galleryImages[index].alt}`}
      </p>
    </div>
  );
}

export default function GalleryDocPage() {
  const { locale } = useLocale();
  const title = meta.gallery.title ?? "Gallery";
  const description = meta.gallery.description ?? "";

  return (
    <ComponentLayout
      title={title}
      description={description}
      usedComponents={[
        { name: "Img", href: "/docs/components/img" },
      ]}
      relatedComponents={[
        { name: "Carousel", href: "/docs/components/carousel" },
        { name: "ImagePreview", href: "/docs/components/image-preview" },
        { name: "MediaLightbox", href: "/docs/components/media-lightbox" },
        { name: "AssetGrid", href: "/docs/components/asset-grid" },
      ]}
    >
      <ComponentPreview codeBlock={<CodeBlock code={usageCode} />}>
        <div className="w-full max-w-sm">
          <Gallery images={galleryImages} aspectRatio="square" />
        </div>
      </ComponentPreview>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0" id="states">
          {locale === "ja" ? "状態とバリエーション" : "States and variants"}
        </h2>
        <p className="text-sm leading-relaxed text-muted-foreground">
          {locale === "ja"
            ? "Gallery が変えられるのは、サムネイルの置き場所（thumbnailPosition）、主画像の比率（aspectRatio）、そして選択を誰が持つか（value と onValueChange）の3つです。矢印キーでの移動と読み上げの配線は、どの組み合わせでも部品側が持ちます。"
            : "Three things vary on a Gallery: where the thumbnail strip sits (thumbnailPosition), the shape of the main image (aspectRatio), and who owns the selection (value with onValueChange). Arrow-key movement and the radiogroup wiring stay with the component in every combination."}
        </p>
        <ComponentDemoStates
          states={[
            {
              key: "thumbnails-start",
              title: locale === "ja" ? "サムネイルを横に置く" : "Thumbnails beside the image",
              description: locale === "ja"
                ? "thumbnailPosition=\"start\" にすると、横幅の広い画面ではサムネイルが左の縦列になります。狭い画面では横並びに戻るので、スマホで縦に長くなりません。"
                : "With thumbnailPosition=\"start\", the strip becomes a vertical column to the left on wide screens and falls back to a row on narrow ones, so it never stretches a phone layout downward.",
              preview: (
                <div className="w-full max-w-md">
                  <Gallery images={galleryImages} thumbnailPosition="start" />
                </div>
              ),
              code: locale === "ja"
                ? `import { Gallery } from "@gunjo/ui";

const images = [
  { src: "/product/front.jpg", alt: "正面" },
  { src: "/product/side.jpg", alt: "側面" },
  { src: "/product/back.jpg", alt: "背面" },
  { src: "/product/detail.jpg", alt: "生地の拡大" },
];

export function SideThumbnailGallery() {
  return <Gallery images={images} thumbnailPosition="start" />;
}`
                : `import { Gallery } from "@gunjo/ui";

const images = [
  { src: "/product/front.jpg", alt: "Front view" },
  { src: "/product/side.jpg", alt: "Side view" },
  { src: "/product/back.jpg", alt: "Back view" },
  { src: "/product/detail.jpg", alt: "Fabric close-up" },
];

export function SideThumbnailGallery() {
  return <Gallery images={images} thumbnailPosition="start" />;
}`,
            },
            {
              key: "aspect-ratio",
              title: locale === "ja" ? "主画像の比率を変える" : "A different main-image shape",
              description: locale === "ja"
                ? "aspectRatio は主画像の枠だけを決めます。物件の内観や車の外観のような横長の写真は \"wide\"、人物や什器の全身は \"portrait\" が合います。枠が先に決まるので、読み込み中でも版面がずれません。"
                : "aspectRatio governs the main image frame only. Interiors and vehicle exteriors read better at \"wide\"; a full-height person or fixture wants \"portrait\". The frame is reserved before the image lands, so the page does not jump while loading.",
              preview: (
                <div className="w-full max-w-md">
                  <Gallery images={galleryImages} aspectRatio="wide" />
                </div>
              ),
              code: locale === "ja"
                ? `import { Gallery } from "@gunjo/ui";

const images = [
  { src: "/room/living.jpg", alt: "リビング" },
  { src: "/room/kitchen.jpg", alt: "キッチン" },
  { src: "/room/bath.jpg", alt: "浴室" },
];

export function RoomGallery() {
  return <Gallery images={images} aspectRatio="wide" />;
}`
                : `import { Gallery } from "@gunjo/ui";

const images = [
  { src: "/room/living.jpg", alt: "Living room" },
  { src: "/room/kitchen.jpg", alt: "Kitchen" },
  { src: "/room/bath.jpg", alt: "Bathroom" },
];

export function RoomGallery() {
  return <Gallery images={images} aspectRatio="wide" />;
}`,
            },
            {
              key: "controlled",
              title: locale === "ja" ? "選択を画面側で持つ" : "The page owns the selection",
              description: locale === "ja"
                ? "value と onValueChange を渡すと、いま何枚目かを画面側が持ちます。枚数の表示や、色を選んだら対応する写真へ飛ばす、といった外からの操作ができるようになります。渡さないときは部品が内部で持ち、defaultIndex が最初の1枚を決めます。"
                : "Passing value with onValueChange moves the active index out to the page. That is what lets a counter track the strip, or a colour choice jump to the matching photo. Omit both and the component keeps the index internally, with defaultIndex picking the first frame.",
              preview: <ControlledGalleryPreview locale={locale} />,
              code: locale === "ja"
                ? `import * as React from "react";
import { Gallery } from "@gunjo/ui";

const images = [
  { src: "/product/front.jpg", alt: "正面" },
  { src: "/product/side.jpg", alt: "側面" },
  { src: "/product/back.jpg", alt: "背面" },
];

export function CountedGallery() {
  const [index, setIndex] = React.useState(0);

  return (
    <div className="flex flex-col gap-2">
      <Gallery images={images} value={index} onValueChange={setIndex} />
      <p className="text-sm text-muted-foreground">
        {index + 1} / {images.length} 枚目：{images[index].alt}
      </p>
    </div>
  );
}`
                : `import * as React from "react";
import { Gallery } from "@gunjo/ui";

const images = [
  { src: "/product/front.jpg", alt: "Front view" },
  { src: "/product/side.jpg", alt: "Side view" },
  { src: "/product/back.jpg", alt: "Back view" },
];

export function CountedGallery() {
  const [index, setIndex] = React.useState(0);

  return (
    <div className="flex flex-col gap-2">
      <Gallery images={images} value={index} onValueChange={setIndex} />
      <p className="text-sm text-muted-foreground">
        Image {index + 1} of {images.length}: {images[index].alt}
      </p>
    </div>
  );
}`,
            },
          ]}
        />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Props</h2>
        <PropsTable data={propsData} />
      </div>

      <div className="space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold tracking-tight first:mt-0">Usage</h2>
        <div className="rounded-md border bg-muted font-mono text-sm max-h-[350px] overflow-auto">
          <CodeBlock code={usageCode} />
        </div>
      </div>
    </ComponentLayout>
  );
}
